### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by benrubson** [jetwhiz/encfs4win#101]
Hi,

I computed some performance numbers about Dokany :
https://github.com/dokan-dev/dokany/issues/670

_For this I used rsync (the Cygwin version) in dry-run mode (-an), syncing to an empty place a directory containing around 10.000 (sub)*directories and 1.000.000 files.
Goal is then to see if Dokany has an impact on the time needed to stat all the files._

Doing this, I tested both EncFS RC12 and RC13.
And I found that RC13 is slower than RC12.

Any reason why it may be like this ?

Thank you very much 👍 

Ben

**Comment by jetwhiz** [comment]
Hi @benrubson -- that's very strange ... the only thing I can think of that changed would be moving to easyloggingpp v9.89 (from v9.83), which happened between RC12 and 13.  I'll see if we can change to the latest (v9.96.1) for the next RC, though they made major API changes after v9.89.  

It might also be good to bump to the latest tinyxml2 version.

**Comment by benrubson** [comment]
Thank you for your answer @jetwhiz.
Well, don't worry updating again & again libraries, furthermore if they introduce incompatibilities...
Perhaps simply use same versions as in upstream EncFS ?
