### ISSUE TITLE
Not possible to mount to drive a or b?

### ISSUE THREAD

**Issue by cyberpunkbln** [jetwhiz/encfs4win#104]
Hello,

i have only a short question. If i take the alarm seriously, that i should not take mountpoints instead of drive-letters (i use it tough;)) i want to use the old fd-drive letters a and b, to prevent some things.

But i can mount all letters but not a or b?

thx

**Comment by jetwhiz** [comment]
Hello @cyberpunkbln 

In Windows it is usually best to avoid mounting to drive letters A and B.  I believe Dokany will allow you to mount to drive B, however, but there may be unintended quirky consequences with Windows and various software (though I can confirm that mounting encfs to B: seems to work correctly for simple tests at least).

**Comment by cyberpunkbln** [comment]
Hello @jetwhiz ,
yes B works A not;), i have only tested A and thought B not,too;). Strange B will be shown as old FD-Drive;).

**Comment by cyberpunkbln** [comment]
Hello,

short question to this->

Why Dokan don't support Drive A but Drive B?  Must i write a issue at dokan repo? I don't find that problem there?

thx

**Comment by jetwhiz** [comment]
@cyberpunkbln  I'm not sure if this has changed in the most recent release of Dokany or if mounting to A and B are hit-or-miss with certain setups, but it now appears that I can mount correctly to drive A. Can you confirm?
