### ISSUE TITLE
Feature-Request Name the mounted drive and use an external config file

### ISSUE THREAD

**Issue by cyberpunkbln** [jetwhiz/encfs4win#107]
Hello,

short Feature Request i have seen in other Projects.

1. Set the name of an Mounted-Drive.
2. Use external config files at creation and mounting encfs-volumes.

thx

**Comment by jetwhiz** [comment]
Hi @cyberpunkbln 

1. Are you referring to a drive label?  If so, then you can already pass this in via: 
  `encfs.exe ... -o volname="label"`
2. You can do this by setting the `ENCFS6_CONFIG` environment variable, see: [encfs.pod#environment-variables](https://github.com/jetwhiz/encfs4win/blob/master/encfs/encfs.pod#environment-variables).  
  This will be possible to specify on the command line in the future (it was recently added to encfs upstream, but will not make it into this release candidate yet).

**Comment by cyberpunkbln** [comment]
Hello,
ah thx, i have only looked with an solve my mountpoints problems eye, when i use -H ;I), sorry. 
thx
