### ISSUE TITLE
How to remove no longer used mount/entries from EncFS GUI? thanks

### ISSUE THREAD

**Issue by ccchan234** [jetwhiz/encfs4win#111]
# Environment
 * Windows version: 
win7 pro, 64bit
 * Processor architecture: 
i7-4790
 * Encfs4win version: 
v1.10.1-RC13
 * Dokan version (legacy, modern): 
modern
# Description 
EncFS GUI allow us to easy ADD encrypted folder/unencrypted folder pair, but how to remove no longer
used ones? I don't find any way to do so! Thx

## Expected behavior vs. actual behavior 
should provide a way to remove no longer used folder pairs.
now, can only add, cannot remove, the list will be way too long after some time.

## Steps to reproduce problem
1. adding a lot of folder pairs

# Relevant logs

Attach any relevant log files that can help to debug your issue (be sure to use the -v option for verbose logs).

**Comment by ccchan234** [comment]
Also, if one cant remove the folder pair, how to CHANGE the destination drive letter too?

I.e., the "remove" function is needed to CHANGE drive letter.

Thanks

**Comment by jjling2011** [comment]
When you mount a folder that does not exist, encfs4win prompts you to remove it from the list.
So renaming the encrypted folder will do the trick.
But I agree with you, encfs4win should provide a way to remove or modify mount point.

**Comment by ccchan234** [comment]
ok thz.

btw i turn to use the command line one.
they differ in block/block32 option.

indeep i turn to another solution as i met bsod in encfs4win after 49gb of lots of files.
