### ISSUE TITLE
Feature request: Show encfs4win version and Dokan version in "About" dialog

### ISSUE THREAD

**Issue by juliojgd** [jetwhiz/encfs4win#115]
As of v. 1.10.1-RC13 when "About" dialog is shown it only prints 
![image](https://user-images.githubusercontent.com/28807086/44629979-43d3c100-a957-11e8-8c34-f60b776377f3.png)

I will be very useful and informative if it shows two more pieces of data:
encfs4win version that is running
Dokan library version that is using.

Thanks in advance.

**Comment by jetwhiz** [comment]
RC14 should have this feature!
