### ISSUE TITLE
Different binary files in v1.10.1-RC13 (ERROR: Unable to load Dokan FUSE library)

### ISSUE THREAD

**Issue by heX16** [jetwhiz/encfs4win#116]
# Environment
 * Windows version: 7
 * Processor architecture: x64
 * Encfs4win version: v1.10.1-RC13
 * Dokan version (legacy, modern): 1.2.0.1

# Description 
Different binary file in two archive.

encfs-installer.exe:
encfs.exe - 446 464 byte.

encfs-installer-legacy.exe
encfs.exe - 487 424 byte.

And in "legacy" version i have error:
```ssh
>encfs.exe
2018-10-16 09:22:26,109 ERROR [default] ERROR: Unable to load Dokan FUSE library
>encfs --version
2018-10-16 09:22:55,124 ERROR [default] ERROR: Unable to load Dokan FUSE library
```

In full version (encfs-installer.exe) all work good.

**Comment by jetwhiz** [comment]
Hi @heX16 

It is not possible to have both encfs legacy and encfs installed at the same time, since they depend on conflicting Dokany libraries to be installed.  Have you tried completely uninstalling encfs and Dokany v1 before trying to install encfs legacy?

**Comment by heX16** [comment]
@jetwhiz i am not sure.

What's the difference between "legacy" and "not legacy" ?

**Comment by jetwhiz** [comment]
@heX16 encfs legacy is only provided for backwards compatibility with the older (legacy) version of the Dokan filesystem.  It is recommended to use encfs modern, as this will be the only version that we will be releasing in the future.
