### ISSUE TITLE
Insert a disk error with latest version

### ISSUE THREAD

**Issue by ajeecai** [jetwhiz/encfs4win#121]
## Environment
 * Windows version: 
Windows 7
 * Processor architecture: 
Intel Core2 Duo CPU
 * Encfs4win version: 
EncFS 1.10.1-RC13
 * Dokan version (legacy, modern): 
Dokan Library 1.1.0.2000 Bundle
## Description 
Could not Open the encrypted folder, after input password, popup a dialog saying "Please insert a disk". It used to work well, after some time it will happen. Reboot can't resolve this issue.

## Expected behavior vs. actual behavior 
It used to work, but this will happen occasionally, then some day later it will recover again.

## Steps to reproduce problem
I don't know how to reproduce
## Relevant logs
Don't know how to capture the log, where the log is located. The screen capture is attached. 

![insert](https://user-images.githubusercontent.com/3023271/50746080-57c5f280-1268-11e9-8520-d7c47099c1e0.png)

**Comment by jetwhiz** [comment]
Hi @ajeecai 

This sounds like it may be related to issue #120 affecting Windows 7.  Could you please test the latest release, [Encfs v1.10.1-RC14](https://github.com/jetwhiz/encfs4win/releases/tag/v1.10.1-RC14), and see if this fixes your issue?

**Comment by ajeecai** [comment]
Hi jetwhiz, 

The problem comes up again, even I have uninstalled Dokany and Encfs and reinstall with Encfs v1.10.1-RC14. 
To answer your question, the previous installation is EncFS 1.10.1-RC13 and Dokan Library 1.1.0.2000 Bundle. Now with RC14, Dokan is Dokan Library-1.2.1.  I don't know if EncFs has some log that I could take a look.

Thanks

**Comment by jetwhiz** [comment]
Is this using the encfsw.exe GUI or with the command line encfs.exe tool?  If you're using the command line tool you can add "-vf" to see log output and keep the window in the foreground.  

Does this issue only happen after having unmounting on that drive letter before, or even on a fresh boot?  It sounds like the drive letter might now be getting freed up and is still being used.  Does the drive appear mounted (shows up in My Computer) when you're having this issue?

**Comment by jetwhiz** [comment]
@ajeecai -- this may be related to a known Dokany FUSE library issue. 

Can you try using the updated version: [v1.10.1-RC15](https://github.com/jetwhiz/encfs4win/releases/tag/v1.10.1-RC15).  Make sure you uninstall both the old encfs4win and old Dokany before installing RC15 (to be sure that Dokany properly upgrades).

**Comment by ajeecai** [comment]
Thank you, I will try and let you know. If it still doesn't work I will try to get  the log as you instruct. It has been crazily busy in the past days...
