### ISSUE TITLE
Bluescreen when copying/deleting on the mount - KERNEL_SECURITY_CHECK_FAILED

### ISSUE THREAD

**Issue by oldenj** [jetwhiz/encfs4win#122]
# Environment
 * Windows version: 10, current updates
 * Processor architecture: x64
 * Encfs4win version: v1.10.1-RC14
 * Dokan version (legacy, modern): modern
# Description 
I have set up an encfs directory within a network cifs share (X:\encfs).
This is mounted to e.g. U:\ .
I can copy and delete files from U:\ , but i got bluescreens "KERNEL_SECURITY_CHECK_FAILED" when copying an existing folder from a share into U:\ and also when trying to delete everything on U:\ .
My best guess is that it is related to files with the "zone bit" set (https://blog.codingoutloud.com/2010/03/05/the-project-location-is-not-trusted-dealing-with-the-dreaded-unblock/).
Unusual is that i may proceed copying the folder after a bluescreen and it gets further until crashing again, to be repeated until all data is copied over.
I'll keep trying to narrow down the issue and get more log contents in the meantime.

## Expected behavior vs. actual behavior 
Data should be copied/deleted as usual.
Actual behaviour: Bluescreen "KERNEL_SECURITY_CHECK_FAILED"

## Steps to reproduce problem
1. Mount an encfs folder to a drive
2. Copy/delete a folder into/from the mount containing non-trusted files

# Relevant logs

I attached a corresponding windows minidump, github doesn't accept the .dmp file extension so i added a .txt suffix.
[encfs-minidump.dmp.txt](https://github.com/jetwhiz/encfs4win/files/2864531/encfs-minidump.dmp.txt)

**Comment by jetwhiz** [comment]
Hi @oldenj ... thanks for this report!  

Any bluescreens are likely a result of something happening in the underlying Dokany library.  It seems there is an outstanding BSOD issue related to locking in Dokany: https://github.com/dokan-dev/dokany/issues/764.  Does this sound similar to what you're experiencing?

**Comment by oldenj** [comment]
Thanks for your reply.
By now i can reproduce the problem reliably and i've found out that it has nothing to do with blocked files, but actually with Symantec Encryption Desktop (dokan-dev/dokany#304).
I will try to figure it out with them.
