### ISSUE TITLE
two prolems. ( Unalble to use)

### ISSUE THREAD

**Issue by JackalJohn** [jetwhiz/encfs4win#123]
# Environment
 * Windows version: 1809
 * Processor architecture:  x64
 * Encfs4win version: 1.10.1
 * Dokan version (legacy, modern): 1.2.1.2000

# Description 
first issue "error saving configuration file"
second issur, software crack when open existed encfs folder created by MixPlorer

## Steps to reproduce problem
1. just installed the exe installer, then I tried to create a container, after setting the passwd and hit OK, the error "error saving configuration file" popped up.

2. I tired to open a existing container created by MixPlorer, but after hitting ok, the encfs4win cracked, without any hint or error pop up, it just disappeared in the progress list! 

# Relevant logs

here is the xml description in the encfs container created by Mixplorer:

.encfs6.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="9">
 <cfg class_id="0" tracking_level="0" version="20">
	<version>20100713</version>
	<creator>MiXplorer-版本: 6.28.3  B1805261</creator>
	<cipherAlg class_id="1" tracking_level="0" version="0">
		<name>ssl/aes</name>
		<major>3</major>
		<minor>0</minor>
	</cipherAlg>
	<nameAlg>
		<name>nameio/block</name>
		<major>3</major>
		<minor>0</minor>
	</nameAlg>
	<keySize>192</keySize>
	<blockSize>1024</blockSize>
	<uniqueIV>0</uniqueIV>
	<chainedNameIV>0</chainedNameIV>
	<externalIVChaining>0</externalIVChaining>
	<blockMACBytes>0</blockMACBytes>
	<blockMACRandBytes>0</blockMACRandBytes>
	<allowHoles>1</allowHoles>
	<encodedKeySize>44</encodedKeySize>
	<encodedKeyData>xlkGlddFdywYVwaAFqelmvs1JcIT03bTGumOgu/+wPXYHMQQnPuxrG4jF6g=

</encodedKeyData>
	<saltLen>20</saltLen>
	<saltData>C5tcbvGaC0ch1FF8fWVtVgIQAs8=

</saltData>
	<kdfIterations>5000</kdfIterations>
	<desiredKDFDuration>500</desiredKDFDuration>
  </cfg>
</boost_serialization>

```
Attach any relevant log files that can help to debug your issue (be sure to use the -v option for verbose logs).

**Comment by jetwhiz** [comment]
Hi @JackalJohn 

I'm guessing you're using the encfsw GUI ... can you try running encfs from the command line:  `encfs.exe -v C:\My\Folder\ Z:` so we can get some debug logs? There should be some sort of error printing out before the `error saving configuration file` error. 

This will output logs for encfs, which are typically stored in `%TEMP%`.

**Comment by jetwhiz** [comment]
@JackalJohn -- this may be related to a known Dokany FUSE library issue. 

Can you try using the updated version: [v1.10.1-RC15](https://github.com/jetwhiz/encfs4win/releases/tag/v1.10.1-RC15).  Make sure you uninstall both the old encfs4win and old Dokany before installing RC15 (to be sure that Dokany properly upgrades).
