### ISSUE TITLE
How to use this in Windows if I already have .encfs6.xml?

### ISSUE THREAD

**Issue by syaifulnizamyahya** [jetwhiz/encfs4win#124]
This is my current linux command.

> echo password | ENCFS6_CONFIG='/storage/downloads/Tool/RcloneTool/.encfs6.xml' encfs \
> -S -o rw -o allow_other -o uid=99 -o gid=100 \
> /storage/downloads/mount/ijm/encfs \
> /storage/downloads/mount/encfs
> 

How do I create a similar command but for windows? 

This is what I tried but failed.
> echo 258456 | ENCFS6_CONFIG='C:/Users/xx/Downloads/cloud/encfs/.encfs6.xml' encfs \
> -S -o rw -o allow_other -o uid=99 -o gid=100 \
> 'C:/Users/xx/Downloads/cloud/mount/gdrive/encfs' \
> 'C:/Users/xx/Downloads/cloud/mount/encfs'

Here are the errors.

> C:\Program Files (x86)\encfs>echo 258456 | ENCFS6_CONFIG='C:/Users/xx/Downloads/cloud/encfs/.encfs6.xml' encfs \
> 'ENCFS6_CONFIG' is not recognized as an internal or external command,
> operable program or batch file.
> 
> C:\Program Files (x86)\encfs>-S -o rw -o allow_other -o uid=99 -o gid=100 \
> '-S' is not recognized as an internal or external command,
> operable program or batch file.
> 
> C:\Program Files (x86)\encfs>'C:/Users/xx/Downloads/cloud/mount/gdrive/encfs' \
> ''C:' is not recognized as an internal or external command,
> operable program or batch file.
> 

Thanks.

**Comment by syaifulnizamyahya** [comment]
I have updated my command to

But I still have problems.

```
C:\Program Files (x86)\encfs>encfs -S -o rw -o allow_other -o uid=99 -o gid=100 "C:\Users\xx\Downloads\cloud\mount\gdrive\encfs" Y:
123456
Error decoding volume key, password incorrect
```

'123456' is the password(not the real one of course. but it consist of only numbers.) The password is so simple and I did not put wrong password.

As for encfs configuration, I put in environment variable 
`ENCFS6_CONFIG=C:\Users\xx\Downloads\cloud\encfs\.encfs6.xml`

Not sure whats wrong. Please help.

Thanks.

**Comment by syaifulnizamyahya** [comment]
Ok. It turns out I need to restart cmd after updating env var.

One I did that,

> C:\Program Files (x86)\encfs>encfs -S -o rw -o allow_other -o uid=99 -o gid=100 "C:\Users\xx\Downloads\cloud\mount\gdrive\encfs" Y:
> 258456

It seems to have no problems. Unfortunately, drive Y is not mounted and nothing is in drive y
C:\Program Files (x86)\encfs>

**Comment by jetwhiz** [comment]
Hi @syaifulnizamyahya 

It looks like this was a known issue with the underlying Dokany FUSE library.  Can you try using the updated version: [v1.10.1-RC15](https://github.com/jetwhiz/encfs4win/releases/tag/v1.10.1-RC15)

Make sure you uninstall both the old encfs4win and old Dokany before installing RC15 (to be sure that Dokany properly upgrades).

**Comment by syaifulnizamyahya** [comment]
It works!
Thanks.
