### ISSUE TITLE
File exists but is not listed with dir on windows nor with ls on linux

### ISSUE THREAD

**Issue by ephestione** [jetwhiz/encfs4win#125]
# Environment
 * Windows version: 10
 * Processor architecture: x64
 * Encfs4win version: latest stable RC15
 * Dokan version (legacy, modern): modern

# Description 
File manager doesn't list several files in the mounted folder, but if instead of "dir" I do "dir filename" or "type filename" on commandline the file is shown. Happens with EncFSMP, with encfs4win, and with encfs on Ubuntu (with ls instead of dir, and cat instead of type), by mounting the same source folder (which is a dropbox subfolder). Said files are NOT set as hidden.

## Expected behavior vs. actual behavior 

File exists and IS shown via a folder listing command vs. file exists but is not shown in folder listing commands.

## Steps to reproduce problem
1. ?? Wouldn't know, I used a dropbox contained encrypted source folder as a work drectory for years, just now I realize some files that I can access (it's a webserver from where Apache can serve all the files, even those "missing"... and index.php is among the ones that aren't shown with dir command, nor ls on ubuntu, but work when requested by http clients)

# Relevant logs

Attach any relevant log files that can help to debug your issue (be sure to use the -v option for verbose logs).
(wouldn't know how to produce them)

**Comment by jetwhiz** [comment]
Hi @ephestione 

This sounds like it might be a known issue upstream with using encfs with Dropbox.  

I would recommend looking at these two upstream issues for guidance on how to get this working: 
 * https://github.com/vgough/encfs/issues/388
 * https://github.com/vgough/encfs/issues/141

This is particularly true if you have External IV Chaining enabled.
