### ISSUE TITLE
Performance on Samba share

### ISSUE THREAD

**Issue by blinkenlight** [jetwhiz/encfs4win#129]
# Environment
 * Windows version: Windows 7 x64
 * Processor architecture: AMD Phenom II X4 955 quad core
 * Encfs4win version: 1.10.1 release
 * Dokan version (legacy, modern): v1.2.2.1000 modern

# Description 
I'm using encfs4win on a windows 7 desktop client to access a Samba share from an Ubuntu 14.04.6 LTS server, both machines on my desk, both with Gigabit Ethernet, plugged into the same Gigabit switch. Typical transfer speed for reading a 1GB file from any of my shares on the server is about 100 megabytes per second. However, either writing or reading a file through the Dokany drive (which stores its data on a Samba share on the server) I get 2.5-3 megabytes per second - which is excruciatingly slow even for said 1GB file. At the same time, copying the **encrypted** version of the exact same file without going through Dokany/encfs (simply using windows explorer on the network share) yields the normal 100 MB/s speed. The encfs drive was freshly created with this version from the windows machine, using "paranoia" mode, with the sole difference of setting "externalIVChaining" back to zero manually in the config xml immediately after the drive was created, before any files were written.

## Expected behavior vs. actual behavior 
One would expect similar performance to plain copying of files, not such a dramatic slow-down.

## Steps to reproduce problem
1. Create an encrypted drive on a Samba network share from a different machine; observe Dokany/encfs read/write speed compared to direct read/write to the same share on the same machine

# Relevant logs
N/A

**Comment by syaifulnizamyahya** [comment]
Decryption might be the cause for the slow down. Try eliminating decryption factor and try again.

**Comment by jetwhiz** [comment]
Hi @blinkenlight 

I agree with @syaifulnizamyahya , especially since you're doing this in paranoia mode and over a network share.  

If you check the upstream [PERFORMANCE.md](https://github.com/vgough/encfs/blob/master/PERFORMANCE.md) page, using the standard (non-paranoia) mode and writing directly to an HDD yields a transfer speed of 32 MiB/s.  Using paranoia mode and going over a network share will likely be noticeably slower.

**Comment by blinkenlight** [comment]
I don't quite see how that could be possible - the encryption is supposed to be happening on the windows desktop PC / client where I am running encfs4win, and that quad core PC is basically idling during this, effortlessly, all four cores of it. On the other hand, the Ubuntu Samba server doesn't care what is getting written to or read from it, encrypted or not, it's the same amount of data - and reading it through Windows Explorer manages to get it across lightning fast, at 100MB/s.

Supporting that the problem should logically be with encfs4win is the fact that in trials I since conducted on the same two machines, with the same share, using the exact same Dokan installation except with cppcryptfs (the windows port of gocryptfs) instead of encfs4win, I reliably get about 50MB/s speed (both for reading or writing) instead of 2.5MB/s - clearly, that's still half of the raw transfer speed the two machines are capable of without involving any encryption software, but that's quite acceptable considering the circumstances.

**Comment by jetwhiz** [comment]
If you run this with standard settings (instead of paranoia mode) are you still seeing 2.5MB/s transfer speeds?

**Comment by blinkenlight** [comment]
Yes, I just tested it. New encrypted drive, standard setting, no paranoia, speed is still 2.5MB/s in both directions. Windows total CPU utilization is around 5% the whole time.

To be fair, I don't think this has anything to do whatsoever with any encryption going on at all - I suspect there is something specific in the way encfs4win chooses to connect to a //host/path type SMB/CIFS share that results in a spectacularly inefficient transfer. But the details are way above my head, and this is just a hunch...

**Comment by jetwhiz** [comment]
Yeah you'd expect to see a difference between paranoia and standard modes if that were the issue, so it must be some other sort of bottleneck.  

Could you try testing out our latest [v1.11.0-beta.1](https://github.com/jetwhiz/encfs4win/releases/tag/v1.11.0-beta.1) version and seeing if that fixes the issue?  A lot of changes have happened upstream between our v1.10 and v1.11.

**Comment by blinkenlight** [comment]
I tried the 1.11.0-beta.1 version and the problem is unchanged, unfortunately...
