### ISSUE TITLE
EncFS GUI should create config for case-insensitive file system on Windows.

### ISSUE THREAD

**Issue by pb2004** [jetwhiz/encfs4win#135]
Currently when creating new config for encfs via gui in maingui.cpp function call is for case-sensitive file system:
nameIOIface = BlockNameIO::CurrentInterface(); //https://github.com/jetwhiz/encfs4win/blob/ad8367dc540ce151ec168e27df38d3af1f60be4c/encfs/win/maingui.cpp#L279
and
https://github.com/jetwhiz/encfs4win/blob/ad8367dc540ce151ec168e27df38d3af1f60be4c/encfs/win/maingui.cpp#L296

For case-insensitive fs these 2 lines should call BlockNameIO::CurrentInterface() with true:
nameIOIface = BlockNameIO::CurrentInterface(true);

**To Reproduce**
Create new encfs dir with gui.

**Expected behavior**
Case-insensitive file names in encfs encrypted folder.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Encfs4win version: v1.10.1
 - Dokan version: v1.2.2.1000

**Comment by jetwhiz** [comment]
Thanks for the report, @pb2004 ! 

I think you're right, this should be the same as when run via command line: 

https://github.com/jetwhiz/encfs4win/blob/ad8367dc540ce151ec168e27df38d3af1f60be4c/encfs/FileUtils.cpp#L1027-L1031

Can you test out that change and confirm it fixes the issue on your end?  You can also open a PR if you're interested in helping out!

**Comment by pb2004** [comment]
> 
> 
> Thanks for the report, @pb2004 !
> 
> I think you're right, this should be the same as when run via command line:
> 
> https://github.com/jetwhiz/encfs4win/blob/ad8367dc540ce151ec168e27df38d3af1f60be4c/encfs/FileUtils.cpp#L1027-L1031
> 
> Can you test out that change and confirm it fixes the issue on your end? You can also open a PR if you're interested in helping out!

This change fixes the reported problem. Thanks.

**Comment by jetwhiz** [comment]
Thanks for the confirmation, @pb2004 !   We'll include this fix in the next release

**Comment by jetwhiz** [comment]
This is now fixed with v1.10.2 (via https://github.com/jetwhiz/encfs4win/commit/bd27fcc676894f3456bc30c887eef5ce34f1502e)
