### ISSUE TITLE
Change encrypted file extension

### ISSUE THREAD

**Issue by leochou0729** [jetwhiz/encfs4win#138]
Hello,
  I wonder if it's possbile to not encrypt the file names but add a special file extension to them? Is there a configuration for this? Thanks!

**Comment by jetwhiz** [comment]
Hi @leochou0729 

I would check with the upstream project for changes to the core functionality of encfs: https://github.com/vgough/encfs

encfs4win is mainly just a fork of their project with Windows-based customizations.

**Comment by leochou0729** [comment]
OK, thanks!
