### ISSUE TITLE
After updated windows10 to 2020H1，Can't open folder

### ISSUE THREAD

**Issue by martines2018** [jetwhiz/encfs4win#142]
**Describe the bug**
After updated windows10 to 2020H1，windows build version 19041， mount works fine，but can't open folder

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Processor architecture: [ x64]
 - Encfs4win version: [ v1.11.0-beta1]
 - Dokan version: [ v1.3.1]

**Additional context**
Attach any relevant log files that can help to debug your issue (be sure to use the -v option for verbose logs).

**Comment by jetwhiz** [comment]
@martines2018, have you found this to be an underlying issue in Dokany (as per https://github.com/dokan-dev/dokany/issues/872)?
