### ISSUE TITLE
Show correct file system info in File Explorer

### ISSUE THREAD

**Issue by leochou0729** [jetwhiz/encfs4win#143]
Hello,
I've submitted an issue to Dokany. Please take a look at this link.
https://github.com/dokan-dev/dokany/issues/885

Now the problem has been resolved using a new mount manager option, but there is a side effect that the file system info shows encfs executable instead of NTFS. I wonder which callback function is used to show this info. Is it implemented in encfs? Thanks!

**Comment by jetwhiz** [comment]
Hi @leochou0729 -- you might be able to pull this off by passing the `-ofsname` parameter on to Dokany, such as by doing  `encfs.exe ... -o -ofsname=NTFS` or `encfs.exe ... -o fsname=NTFS`.  Can you try this out and see if that works?

**Comment by leochou0729** [comment]
Hi @jetwhiz,
I've tried "-o fsname=NTFS" and it works.
I have one small question.
If I don't use the mount manager option, the encfs drive can show the correct file system info. Which callback function provides this info? Passing fsname to Dokan seems inflexible because the source directory could be on a FAT32 or exFAT thumb drive. Thanks!
