### ISSUE TITLE
does it support encfs 1.7.4 ?

### ISSUE THREAD

**Issue by kingone51** [jetwhiz/encfs4win#144]
Does it support encfs 1.7.4? Because ANDROID has a file manager called Mixplor, developed by Xda, you can create and Browse encfs 1.7.4 on phone. I'm sorry to bother you, but I really want to use encfs encrypted cloud files on both my computer and my phone.

**Comment by KnIfER** [comment]
yes. you can copy the config xml from your phone to  computer. I'am using encfsWin 1.10.2, and  it will compat with mixplor. however, I cannot  open the encrypted file directly, just being able to copy-and-decrypt the file. do you know whether mixplor is capable of openning encrypted files directly?
