### ISSUE TITLE
Allow all parameters to be passed in via command line

### ISSUE THREAD

**Issue by jetwhiz** [jetwhiz/encfs4win#2]
Creating new encrypted FS or mounting one requires input from stdin 
Config file location passed in through ENV variables

**Comment by imperative** [comment]
This is probably the same in the linux-version as well, so perhaps it's better to report it there so this function can come back here if we ever do a rebase?

**Comment by jetwhiz** [comment]
Hi @imperative -- we already have a pull request to implement this functionality upstream, but we're just waiting for them to complete it.  See vgough/encfs/pull/167 

The relevant feature addition to this issue (#2) is: 
* --config=path - specify config file

**Comment by benrubson** [comment]
https://github.com/vgough/encfs/pull/474 will add `-c / --config` option 👍
