### ISSUE TITLE
encfs.exe crashes upon receiving CTRL + C

### ISSUE THREAD

**Issue by Zero3** [jetwhiz/encfs4win#22]
Just got a Windows 7 crash dialog saying that encfs.exe stopped working. What I did:

1) Downloaded and installed https://github.com/jetwhiz/encfs4win/releases/tag/v1.10.1-RC1

2) Executed encfs.exe [path to non-existing folder] Z:

3) Completed the encfs encryption setup steps

4) Pressed CTRL + C

The last console output was:

````
2016-04-30 21:27:01,113 FATAL [default] CRASH HANDLED; Application has crashed due to [SIGINT] signal
2016-04-30 21:27:01,113 WARN  [default] Aborting application. Reason: Fatal log at [C:\win\Projects\Keenou\encfs4win\deps\easyloggingpp\src\easylogging++.h:5583]
````

I would expect encfs.exe to gracefully unmount and close upon receiving CTRL + C. I assume this would happen during normal system shutdown as well? Or is there another way of running encfs.exe in the background and handling system shutdown gracefully?

**Comment by ultimate-deej** [comment]
Same on Windows 10.
Also when I try to run it again right after Ctrl+C, it closes silently after typing a password. Running it for the second time seems fine.

**Comment by jetwhiz** [comment]
This should be fixed with the latest commit.  Could you guys please test [v1.10.1-RC2](https://github.com/jetwhiz/encfs4win/releases/tag/v1.10.1-RC2)?

**Comment by Zero3** [comment]
Appears to be so! The log message is wrong, though:

````
2016-05-01 11:00:43,147 WARN  [default] Unmounting filesystem due to inactivity: Z:
````

**Comment by jetwhiz** [comment]
Great!  I'll roll the fix for the log message out in the next release.
