### ISSUE TITLE
encfs.exe crashes if closed during mount password promt

### ISSUE THREAD

**Issue by Zero3** [jetwhiz/encfs4win#25]
Similar to https://github.com/jetwhiz/encfs4win/issues/22, encfs.exe crashes if you close its console window (or press CTRL + C) when asked for the password for an encrypted directory during mounting.

I would expect encfs.exe to gracefully exit instead.

**Comment by jetwhiz** [comment]
Hi @Zero3 -- Thanks for reporting this!  I modified the signal handler to take this situation into account, as well as added some cleanup routines.  Can you confirm that this issue is fixed in [1.10.1-RC3](https://github.com/jetwhiz/encfs4win/releases/tag/1.10.1-RC3).

**Comment by Zero3** [comment]
You are welcome! This issue is indeed fixed for me in your latest build. Thanks.
