### ISSUE TITLE
How to cancel logging?

### ISSUE THREAD

**Issue by pyy** [jetwhiz/encfs4win#26]
Hello,

May I ask how to cancel this log function when I build encfs4win myself? I find there is no log folder if I use released version. Where should I edit to disable this function? Thank you.

![log](https://cloud.githubusercontent.com/assets/4225935/15155337/53ba12fe-16e2-11e6-9edf-a41f8f4a7906.JPG)

**Comment by jetwhiz** [comment]
Hi @pyy -- unfortunately this is a known issue with [easylogging++](https://github.com/easylogging/easyloggingpp/issues/336).  So far I haven't been able to find a solution, but I'll see if I can prevent the log from being created.

**Comment by jetwhiz** [comment]
I have created a patch for easylogging++ that will prevent logs from being created.  The patch will automatically be applied if you use the encfs4win build tools (or you can apply it manually, it is in the deps folder).  

This change will be released in 1.10.1-RC6.
