### ISSUE TITLE
How to auto mount after restart computer?

### ISSUE THREAD

**Issue by pyy** [jetwhiz/encfs4win#27]
Hello,

I'm using encfsw.exe of version 1.10.1-RC4, it can start with system but cannot auto-mount with system start. I have to mount it manually.

Is there a bash command I can put in to startup to mount it automatically when the system start? Thank you.

Thank you. Bests to all the contributors.

**Comment by jetwhiz** [comment]
Hi @pyy,

Right now this is not possible to do with encfs4win alone (you would have to write a script to pipe your password in).  I wrote a patch that will allow your password to be passed in via the command line, but am still waiting for it to be included in the upstream EncFS project.  

I will keep you updated when this is ready (hopefully sometime this week).

**Comment by jetwhiz** [comment]
@pyy  -- starting with 1.10.1-RC5 you will be able to use the --extpass option in encfs.  This will allow you to auto-mount on system startup.  For example, you can create a file that stores your password (pw.txt, for example) and auto-mount with: 

````cmd
encfs.exe --extpass="cmd /c type pw.txt" C:\mycrypt Z:
````
