### ISSUE TITLE
Error "Please insert a disk into Removable Disk" on Windows 10

### ISSUE THREAD

**Issue by wezeku** [jetwhiz/encfs4win#28]
This is a weird one, because I get this error on a Windows 10 laptop but not in a Win10 virtual machine (in VMWare):

![error](https://cloud.githubusercontent.com/assets/4984675/15232630/ec5e2600-18a2-11e6-9027-9c7a2459b7a8.png)

Both the laptop and the virtual machine run Win10 with the latest updates. I get the same result regardless of whether I create a new volume, or copy and existing encfs directory and try to mount it.

**Comment by jetwhiz** [comment]
Hi @wezeku -- I had to replace the hard drive on my computer, so it might take a few more days for me to be able to test this out.  In the meantime, could you test out [v1.9.0-RC4](https://github.com/jetwhiz/encfs4win/releases/tag/v1.9.0-RC4) and see if the issue exists?  I'm wondering if switching away from the Boost library or RLog could be causing this.

**Comment by wezeku** [comment]
I tried 1.9.0-RC4 (with encfsw.exe from 1.10.1-RC4) and it works without error messages. I also noticed that while 1.10.1-RC4 gives the error message, it seems to work anyway.

**Comment by gh223682** [comment]
I've experienced a very similar problem if I start encfs.exe (1.10.1-RC4) early in the login process (Windows 10). The virtual drive which is created doesn't seem to get initialized properly, and only appears as a "Removable Disk" in explorer, for example X:. When I try to open that drive, I get the message

> Please insert a disk into Removable Disk (X:)

I have to kill the encfs.exe process and try again, at which point the virtual drive usually gets mapped correctly.

In an offline conversation, @jetwhiz speculated that:

> This might be some sort of a race condition where encfs is starting before the Dokan FUSE library is loaded.

Through some further testing, I believe that this is indeed the case.

I successfully tested two possible workarounds:

1. Wait a little bit longer into the login process before starting encfs.exe; or
2. Force the Dokan FUSE library to load by issuing a command like 

`% dokanctl.exe /d 0`

So I believe that encfs.exe should incorporate something similar, i.e.:

1. Wait for the Dokan FUSE library to load and exit with a warning after a certain timeout period; and/or
2. Force the Dokan FUSE library to load and exit with a warning if that fails.

**Comment by jetwhiz** [comment]
Hi @gh223682 @wezeku 

Could you test this patch out and see if it helps with the issue?  

[patch.txt](https://github.com/jetwhiz/encfs4win/files/273518/patch.txt)

It essentially just adds these lines to the main function for encfs.exe: 

````C++
  // Ensure we load the dokan library beforehand 
  HINSTANCE hinstLib;
#ifdef USE_LEGACY_DOKAN
  hinstLib = LoadLibrary(TEXT("dokan.dll"));
#else
  hinstLib = LoadLibrary(TEXT("dokan1.dll"));
#endif
  if (hinstLib == NULL) {
    RLOG(ERROR) << "Unable to load Dokan FUSE library";
    return EXIT_FAILURE;
  }
````

**Comment by wezeku** [comment]
In preparation for trying the patch, I uninstalled 1.9.0-RC4  and reinstalled 1.10.1-RC4. When I rebooted and ran 1.10.1-RC4 (unpatched) again, the error message no longer popped up. 

I've updated a few Intel and Lenovo drivers since my first test. This shouldn't affect the problem, but it's the only config difference between my tests that I can think of.

**Comment by jetwhiz** [comment]
@wezeku -- did you notice if Dokan was successfully installed on the machine when it was failing?  

I noticed a problem with the installer, where Dokan would silently fail to install (because dependencies were not met).  This might explain why it works when you installed 1.9.0-RC4 and then re-installed 1.10.1-RC4.  This could explain you "Please insert a disk into Removable Disk" issue.

**Comment by gh223682** [comment]
@jetwhiz Dokany-1.0 also does not uninstall cleanly and leaves system files laying around.

**Comment by gh223682** [comment]
@jetwhiz The latest pre-RC5 patch seems to do the trick. No issues so far.

**Comment by jetwhiz** [comment]
> Dokany-1.0 also does not uninstall cleanly and leaves system files laying around.

@gh223682 Is this when you try running the dokany uninstaller?

**Comment by gh223682** [comment]
> Is this when you try running the dokany uninstaller?
@jetwhiz Yes. I should probably report this issue on that project.

**Comment by wezeku** [comment]
Dokan was correctly installed when I first encountered this problem (I checked specifically, because Dokan was my prime suspect). 

Since I reinstalled 1.10.1-RC4, the problem started occurring occasionally again, so I have applied the patch. So far, no problems. I'll mount an encfs drive at startup from now on, to see how it works in the long run.
