### ISSUE TITLE
Provide compatibility with stable versions of Dokan FUSE library like 0.8.0?

### ISSUE THREAD

**Issue by gh223682** [jetwhiz/encfs4win#29]
If possible, it would be nice to be able to use the stable version of the Dokan FUSE library.

**Comment by jetwhiz** [comment]
Hi @gh223682, 

Right now, the only (real) stable version of Dokan is v0.7.4 (which we should have compatibility with).  Dokany v0.8.0 does not have a working FUSE API (so it cannot be used for encfs4win), and has been essentially abandoned as they work on v1.0.0.  

Have you tested against Dokan v0.7.4?

**Comment by gh223682** [comment]
@jetwhiz Sorry for not being more specific.

Yes, I tried installing EncFS4Win 1.10.1-RC4 without Dokan, and then separately tested with Dokan v0.7.4 and Dokan v0.8.0. Each time, I got the error:

`The program can't start because dokanfuse1.dll is missing from your computer. Try reinstalling the program to fix this problem.`

There don't appear to be any dokanfuse* dll files for Dokan v0.7.4 or v0.8.0.

**Comment by jetwhiz** [comment]
Ah, I see!  Unfortunately your encfs.exe  binaries must be built with the version of Dokan that you're targeting, so you can't take encfs.exe binaries built for Dokany-1.0 and use them with a Dokany 0.7.4 install.  

Maybe I can release encfs4win (built on Dokany-1.0) and encfs4win-legacy (Dokany-0.7.4) installers from now on if that helps?

**Comment by gh223682** [comment]
@jetwhiz The wording in the README.md is what threw me off:

> EncFS4win has been successfully tested with the original release of Dokan (v0.7.x) as well as the latest Dokan (v1.x.x).

If it's going to be extra work, it's up to you whether you think this would be a worthwhile investment of time. Since Dokany-1.0 is nearing stable release, perhaps this will not be necessary.

**Comment by jetwhiz** [comment]
@gh223682 -- the wording is confusing in the README ... I should update it to be more clear.  Maybe this? 

> EncFS4win has been successfully built against the original release of Dokan (v0.7.x) as well as the latest Dokan (v1.x.x).

**Comment by gh223682** [comment]
@jetwhiz That sounds good.

I think if you want to advertise compatibility with Dokan v0.7.4, it makes sense to also provide a legacy build. At the very least, it doesn't hurt because you can always be sure that the latest version will build.
