### ISSUE TITLE
Pull in latest upstream changes 

### ISSUE THREAD

**Issue by jetwhiz** [jetwhiz/encfs4win#3]
Windows seems to rely on open_readonly_workaround to work properly, otherwise there are major permissions issues with readonly files.  

Upstream changes have removed this function, since it is no longer necessary for the *nix variant.  See if we can get the Windows working without needing this workaround, too.

**Comment by kriswebdev** [comment]
Hi jetwhiz, please check this patch: https://github.com/kriswebdev/encfs4win-reloaded/commit/23ebb75c08e2d1567c27ef691b29fbbe64782302

The issue for read access is not about this workaround, it's just a bug.

**Comment by jetwhiz** [comment]
Nice catch ... thanks, kriswebdev!  I'll incorporate that in the next version after I get these read access issues worked out.
