### ISSUE TITLE
encfsw.exe tray icon does not repaint properly and disappears on a taskbar refresh

### ISSUE THREAD

**Issue by gh223682** [jetwhiz/encfs4win#30]
The encfsw.exe tray icon disappears either on a taskbar refresh or restart of the explorer.exe process.

**Comment by jetwhiz** [comment]
Hi @gh223682 ,

I believe this should now be fixed, and will push out the fix in the next release candidate.  Below is the patch, if you would like to test it: 

[patch.txt](https://github.com/jetwhiz/encfs4win/files/273484/patch.txt)

**Comment by gh223682** [comment]
@jetwhiz That seems to do the trick. No issues so far.
