### ISSUE TITLE
Cannot delete files or folders with 1.10.1-RC5 legacy

### ISSUE THREAD

**Issue by gh223682** [jetwhiz/encfs4win#34]
I cannot delete any files or folders when using 1.10.1-RC5 legacy built against Dokan v0.7.4.

To reproduce, simply create a file or folder on the virtual drive then try to delete it.

I experienced this problem using both explorer and native-windows commands. However, I am able to remove files and folders using other programs, for example Cygwin's `rm`.

Perhaps related to issue #24.

**Comment by jetwhiz** [comment]
@gh223682  -- Does this only happen with legacy, or also in modern?

**Comment by gh223682** [comment]
@jetwhiz This particular behavior only happens in legacy, not modern.

**Comment by jetwhiz** [comment]
@gh223682 It looks like the legacy build is working okay on my machine -- you aren't able to delete any files or folders at all on yours?  Do the verbose logs give any useful info?

**Comment by gh223682** [comment]
@jetwhiz I am able to delete (empty) folders but not files, using legacy 1.10.1-RC6 in Windows 10.

When I use modern 1.10.1-RC6, I am able to delete those same folders and files.

Looking at the verbose logs, it appears as if "unlink" is never called with legacy encfs.exe.

Legacy 1.10.1-RC6:

> 2016-05-28 22:04:56,190 VER [encfs.cpp:681] doing statfs of C:\EncFS
> 2016-05-28 22:04:56,190 VER [RawFileIO.cpp:89] open call, requestWrite = 1
> 2016-05-28 22:04:56,190 VER [RawFileIO.cpp:110] open file with flags 2, result = 4
> 2016-05-28 22:04:56,190 VER [encfs.cpp:576] encfs_open for C:\EncFS/test.txt, flags 2
> 2016-05-28 22:04:56,190 VER [RawFileIO.cpp:89] open call, requestWrite = 0
> 2016-05-28 22:04:56,190 VER [RawFileIO.cpp:95] using existing file descriptor
> 2016-05-28 22:04:56,268 VER [encfs.cpp:214] readdir on C:\EncFS

Modern 1.10.1-RC6

> 2016-05-28 23:49:38,327 VER [encfs.cpp:681] doing statfs of C:\EncFS
> 2016-05-28 23:49:38,327 VER [encfs.cpp:214] readdir on C:\EncFS
> 2016-05-28 23:49:38,327 VER [encfs.cpp:214] readdir on C:\EncFS
> 2016-05-28 23:49:38,327 VER [RawFileIO.cpp:89] open call, requestWrite = 1
> 2016-05-28 23:49:38,327 VER [RawFileIO.cpp:110] open file with flags 2, result = 4
> 2016-05-28 23:49:38,327 VER [encfs.cpp:576] encfs_open for C:\EncFS/test.txt, flags 2
> 2016-05-28 23:49:38,327 VER [RawFileIO.cpp:89] open call, requestWrite = 0
> 2016-05-28 23:49:38,327 VER [RawFileIO.cpp:95] using existing file descriptor
> **2016-05-28 23:49:38,327 VER [DirNode.cpp:700] unlink test.txt**
> 2016-05-28 23:49:38,327 VER [encfs.cpp:214] readdir on C:\EncFS

**Comment by jetwhiz** [comment]
Does unlink trigger if you try to remove a file with "DEL" via the command line with legacy?  I don't see anything in the code that's changed with regards to unlinking files.  Legacy can remove empty folders successfully, though?

**Comment by gh223682** [comment]
> Does unlink trigger if you try to remove a file with "DEL" via the command line with legacy? I don't see anything in the code that's changed with regards to unlinking files. Legacy can remove empty folders successfully, though?

@jetwhiz I just tried this again with using "del" via the command line with 1.10.1-RC6 legacy, and I see no "unlink" in the verbose logs and the file is not deleted.

There is also no error, so the user is not notified that the deletion did not occur.

If I repeat using "del" via the command line with 1.10.1-RC6 modern, unlink is triggered and the file is deleted as expected.

**Comment by jetwhiz** [comment]
@gh223682 I'm wondering if this issue is related to the fact that the encfs_create callback was not defined for legacy.  I have added this callback function back in for RC7 -- can you test this version to see if the issue has been fixed?

**Comment by gh223682** [comment]
> I'm wondering if this issue is related to the fact that the encfs_create callback was not defined for legacy. I have added this callback function back in for RC7 -- can you test this version to see if the issue has been fixed?

@jetwhiz Now with legacy 1.10.1-RC7, simply creating a file from the command line or via explorer causes encfs.exe to crash:

> CreateFile : \New Text Document.txt
> 	AccessMode: FILE_GENERIC_WRITE|FILE_GENERIC_READ|WRITE_DAC
> 	ShareMode: 0x0
> 	Disposition: CREATE_NEW (1)
> 	Flags: 128 (0x80)
> 2016-06-09 21:55:41,603 DEBUG [default] [int __thiscall encfs::RawFileIO::getAttr(struct _stat64 *) const] [RawFileIO.cpp:137] getAttr error on C:\EncFS/New Text Document.txt: No such file or directory
> 2016-06-09 21:55:41,603 DEBUG [default] [int __cdecl encfs::withFileNode(const char *,const char *,struct fuse_file_info *,class std::function<int __cdecl(class encfs::FileNode *)>)] [encfs.cpp:146] op: getattr error: No such file or directory
> 2016-06-09 21:55:41,603 VER [encfs.cpp:292] mknod on C:\EncFS/New Text Document.txt, mode 511, dev 0
> 2016-06-09 21:55:41,603 VER [RawFileIO.cpp:89] open call, requestWrite = 1
> 2016-06-09 21:55:41,603 VER [RawFileIO.cpp:110] open file with flags 2, result = 4
> 2016-06-09 21:55:41,603 VER [encfs.cpp:610] encfs_open for C:\EncFS/New Text Document.txt, flags 1282

"del" via the command line with 1.10.1-RC7 does not delete:

> CreateFile : \test.txt
> 	AccessMode: FILE_READ_ATTRIBUTES
> 	ShareMode: FILE_SHARE_DELETE|FILE_SHARE_WRITE|FILE_SHARE_READ
> 	Disposition: OPEN_EXISTING (3)
> 	Flags: 0 (0x0)
> 2016-06-09 22:10:07,416 VER [RawFileIO.cpp:89] open call, requestWrite = 0
> 2016-06-09 22:10:07,416 VER [RawFileIO.cpp:110] open file with flags 0, result = 4
> 2016-06-09 22:10:07,416 VER [encfs.cpp:610] encfs_open for C:\EncFS/test.txt, flags 0
> GetFileInfo : \test.txt
> Cleanup: \test.txt
> 
> Close: \test.txt
> 
> 2016-06-09 22:10:07,416 VER [RawFileIO.cpp:89] open call, requestWrite = 0
> 2016-06-09 22:10:07,416 VER [RawFileIO.cpp:95] using existing file descriptor
> CreateFile : \test.txt
> 	AccessMode: FILE_READ_ATTRIBUTES
> 	ShareMode: FILE_SHARE_DELETE|FILE_SHARE_WRITE|FILE_SHARE_READ
> 	Disposition: OPEN_EXISTING (3)
> 	Flags: 0 (0x0)
> 2016-06-09 22:10:07,416 VER [RawFileIO.cpp:89] open call, requestWrite = 0
> 2016-06-09 22:10:07,416 VER [RawFileIO.cpp:110] open file with flags 0, result = 4
> 2016-06-09 22:10:07,416 VER [encfs.cpp:610] encfs_open for C:\EncFS/test.txt, flags 0
> GetFileInfo : \test.txt
> Cleanup: \test.txt
> 
> Close: \test.txt

**Comment by jetwhiz** [comment]
@gh223682  I've tested this out with 1.10.1-RC7 legacy on both Windows 7 (32-bit) and Windows 10 (64-bit) but have not been able to replicate the bug.  On my machines, the folders and files all get deleted as normal.  
 
Can you give more details about your particular setup?

**Comment by jetwhiz** [comment]
Hi @gh223682 -- do you know if this problem still exists with the latest version of encfs (now [1.10.1-RC-8](https://github.com/jetwhiz/encfs4win/releases/tag/1.10.1-RC8))?   From what I can tell on my end, this problem no longer exists, so I believe it is safe to close this issue.   

Please report any new issues if this problem still exists with the latest version.

**Comment by gh223682** [comment]
@jetwhiz I'm doing some testing with encfs 1.10.1-RC8 legacy on Windows 10 64-bit and I'm still having issues deleting certain files.

One specific case is if I create a file and save a file in Excel, I cannot delete the lock/temporary file which is created, obviously after exiting Excel. Deleting the file in explorer.exe does not report an error, but when I refresh, the file is still there.

Also, I've run into another issue where I tried deleting a non-empty folder which was only three levels deep and contained a few dummy files that I created, and got a "Item Not Found" error for a file which could not be found.

**Comment by jetwhiz** [comment]
Hi @gh223682 -- is there anything in the verbose logs when a file is unsuccessfully deleted?  I know there are issues with Windows in general with deleting files (even outside of encfs), since Windows has a weird locking mechanism that doesn't seem to ever want to let go of files and folders.
