### ISSUE TITLE
Add install location to registry

### ISSUE THREAD

**Issue by Zero3** [jetwhiz/encfs4win#36]
It would be nice if the encfs4win installer added the install location to the registry. This would make it easy for external utilities (such as the tray manager I'm working on) to detect whether encfs4win is installed, and to where, in order to call encfs.exe.

**Comment by jetwhiz** [comment]
This will be included in the installer starting with RC7 -- look for the registry key at: 

HKLM "Software\encfs" "Install_Dir"
