### ISSUE TITLE
Remove man page reference

### ISSUE THREAD

**Issue by Zero3** [jetwhiz/encfs4win#37]
When encfs4win is run without any command line parameters, the following line is present in the output:

````
For more information, see the man page encfs(1)
````

In the Windows world, a man page reference is not very helpful, and not likely to be understood by the user. I suggest removing the reference and pointing the user towards any additional documentation in way that is more user-friendly for Windows users.

**Comment by jetwhiz** [comment]
Maybe we should just include a link to the project homepage or https://github.com/jetwhiz/encfs4win?

**Comment by Zero3** [comment]
Yeah, that would probably be fine for now :).
