### ISSUE TITLE
Migrate to Dokan 0.8.0

### ISSUE THREAD

**Issue by jetwhiz** [jetwhiz/encfs4win#4]
Latest stable version of Dokan is now 0.8.0

**Comment by kriswebdev** [comment]
Hi,
I recommend porting to Dokany 1.0.0 beta so that we can use Paragon ExtFS along with Encfs4Win. Very useful for mounting Linux extfs drives with some encfs-encrypted folders on it.
See https://github.com/dokan-dev/dokany/issues/129

**Comment by jetwhiz** [comment]
Hi @kriswebdev 

I have opened this as a new issue: #7.  Although there are no API changes between 0.8 and 1.0, I'm not confident that unexpected things might break now that the dokany project has moved to a semantic versioning system.  I figure it is safer to push up to 0.8 (stable), and then hopefully moving to 1.0 (beta) will be quick and easy after that.

**Comment by Driim** [comment]
There are no API changes, so migrating to 1.0.0 will be done automatically. But beta version have [differences ](https://github.com/dokan-dev/dokany/issues/158) with release version, so i suggest to wait release

**Comment by jetwhiz** [comment]
Hey @Driim! 

Under "compatwin.cpp" I noticed there are a lot of shim-like functions pulled in from Dokany 0.7.x.  Are there no equivalents available in 0.8.x?   From what I understand these will be re-introduced in the 1.x line, so these should all only be temporary for while we're on 0.8.x.

**Comment by Driim** [comment]
Yes you are right. They will be in 1.x But dokany 0.8.0 has broken fuse support

**Comment by Liryna** [comment]
Hi @Driim @jetwhiz ,

There is a pull request in the fuse API of dokan:
https://github.com/dokan-dev/dokany/pull/166
https://github.com/dokan-dev/dokany/pull/167

Did you faced issue when deleting folders ?

**Comment by Liryna** [comment]
@Driim 
Dokan 1.0.0-RC1 has been released https://github.com/dokan-dev/dokany/releases/tag/v1.0.0-RC1
It include you changes and https://github.com/dokan-dev/dokany/pull/167

If you need https://github.com/dokan-dev/dokany/pull/166 for the stable release, please tell me.

**Comment by jetwhiz** [comment]
Hi @Liryna 

Yes I am noticing this issue with the 0.8.0 release (which is fixed on my end by #166).  Also, it is impossible to rename files or directories from what I can tell (it says that the file or folder does not exist when trying to rename).  Perhaps this is a separate issue?

**Comment by Driim** [comment]
1.0.0 released it's great! I will test as soon as i can, now I am busy. And see were i can help.

**Comment by Driim** [comment]
I also had this issues(delete dirs and rename files). I had [patch](https://github.com/Driim/WinEncFS/commit/96ca5fceee43c13a4b63dc3d48fd786f0bcfbb6c) that return logging to encfs, so i will try to debug rename file issue.

**Comment by jetwhiz** [comment]
Hi @Driim @Liryna 

From what I can tell, our "fuse_operations" object is never triggering our "encfs_rename" callback upon file rename in Windows.  

```c++
  fuse_operations encfs_oper;
  memset(&encfs_oper, 0, sizeof(fuse_operations));
  encfs_oper.rename = encfs_rename;

... 

int encfs_rename(const char *from, const char *to) {
	rDebug("============================ ENCFS_RENAME BEGIN ========================");

... 

```

From the code block above, the debug line is never output when an attempt to rename a file occurs.  Also, there are no errors thrown during program execution.  If this looks like a bug that we can fix on our side then I will open an issue for our 0.8-dokany milestone.
