### ISSUE TITLE
Cannot mount virtual drive from Remote Desktop session

### ISSUE THREAD

**Issue by gh223682** [jetwhiz/encfs4win#40]
# Environment
 * Windows version: Windows 10
 * Processor architecture: amd64
 * Encfs4win version: 1.10.1-RC6
 * Dokan version (legacy, modern): modern

# Description 

encfs.exe does not complete process of mounting virtual drive when launched from a Remote Desktop session.

The encfs.exe process does not exit or crash, and debugging logs do not provide useful information.

## Expected behavior vs. actual behavior 

User should be able to mount virtual drives regardless if launched from normal desktop session or remote desktop session.

## Steps to reproduce problem

1. Run encfs.exe from a Remote Desktop session.

# Relevant logs

2016-05-29 02:19:08,278 VER [main.cpp:671] Root directory: C:\EncFS/
2016-05-29 02:19:08,278 VER [main.cpp:672] Fuse arguments: (fg) (encfs) (threaded) (keyCheck) C:\PROGRA~2\EncFS\encfs.exe X: -f -o use_ino 
2016-05-29 02:19:08,371 VER [FileUtils.cpp:296] found new serialization format
2016-05-29 02:19:08,371 VER [FileUtils.cpp:310] subVersion = 20100713
2016-05-29 02:19:08,371 VER [Interface.cpp:110] checking if ssl/aes(3:0:2) implements ssl/aes(3:0)
2016-05-29 02:19:08,371 VER [SSL_Cipher.cpp:328] allocated cipher ssl/aes, keySize 32, ivlength 16
2016-05-29 02:19:08,434 VER [Interface.cpp:110] checking if ssl/aes(3:0:2) implements ssl/aes(3:0)
2016-05-29 02:19:08,434 VER [SSL_Cipher.cpp:328] allocated cipher ssl/aes, keySize 32, ivlength 16
2016-05-29 02:19:08,450 VER [FileUtils.cpp:1611] cipher key size = 52
2016-05-29 02:19:08,450 VER [Interface.cpp:110] checking if nameio/block(4:0:2) implements nameio/null(1:0)
2016-05-29 02:19:08,450 VER [Interface.cpp:110] checking if nameio/block32(4:0:2) implements nameio/null(1:0)
2016-05-29 02:19:08,450 VER [Interface.cpp:110] checking if nameio/null(1:0:0) implements nameio/null(1:0)

**Comment by gh223682** [comment]
This appears to be related to a Dokany Issue: Mount failure in Windows Terminal Services session because the Volume device is inaccessible

https://github.com/dokan-dev/dokany/issues/240

**Comment by jetwhiz** [comment]
We'll keep an eye on what happens upstream ...

**Comment by jetwhiz** [comment]
> After investigation it seems to be related to BroadcastSystemMessage taking a lot of time (something like 30sec on my side). I don't know why here and it may be related to the system on something out of Dokan scope. Anyway KeepAlive and Loop threads should be created before forcing all applications to realize about the new mount point ; and this seems to fix the issue (BroadcastSystemMessage will still hang but mount will not fail).

Can you confirm this behavior?  Will the mount successfully complete after a few minutes of waiting?

**Comment by gh223682** [comment]
@jetwhiz encfs.exe is actually exiting without providing any useful information.

Here are the contents of the log file:

> 2016-06-06 17:06:53,211 VER [main.cpp:534] Closing stderr
> 2016-06-06 17:06:54,321 VER [openssl.cpp:47] Allocating 41 locks for OpenSSL

**Comment by gh223682** [comment]
> Can you confirm this behavior? Will the mount successfully complete after a few minutes of waiting?

@jetwhiz I have tried to reproduce this behavior, and I cannot. But it appears as if something is going on now which is causing encfs.exe to exit.

I haven't been able to figure out what is different now than when I created this issue, as I've been making lots of changes to my new Windows 10 installation with system settings, anti-virus, forced updates installed automatically by the operating system, etc.

Can you have encfs.exe provide more useful debugging information, particularly during the initialization and mounting process?

**Comment by jetwhiz** [comment]
@gh223682  Can you try mounting using the "-d" debug flag for Dokany?   

For instance: 
````cmd
encfs.exe path mountpoint -- -d
````

The output isn't very useful, but it's all that is available.  From the perspective of encfs, the mounting process is very simple (we just call on fuse_main()).

**Comment by jetwhiz** [comment]
@gh223682 -- Since encfs4win [1.10.1-RC8](https://github.com/jetwhiz/encfs4win/releases/tag/1.10.1-RC8) is built against Dokany 1.0.0-RC4, these issues should now be taken care of.  Please let me know if you still experience any issues with the latest release.

**Comment by gh223682** [comment]
@jetwhiz I am not experiencing this problem so far with encfs4win 1.10.1-RC8 built against Dokany 1.0.0-RC4.

**Comment by thedewi** [comment]
This is still happening on my system with RC10, but after learning of ```-d``` above, I found a workaround: in RDP I need to run ```encfsw.exe``` or ```encfs.exe``` as Administrator. It doesn't trigger a UAC prompt. Perhaps ```encfsw.exe``` could detect when UAC is necessary, and ```encfs.exe``` could output more information about Dokan errors.

Thanks for reviving this project - I'd been looking out for it for years and it has come together very well.
