### ISSUE TITLE
encfsctl cat mangles newlines

### ISSUE THREAD

**Issue by RunasSudo** [jetwhiz/encfs4win#41]
# Environment
 * Windows version: Windows 7, wine
 * Processor architecture: x86, x64
 * Encfs4win version: 1.10.1-RC6
 * Dokan version (legacy, modern): modern

# Description 
`encfsctl cat` converts *all* instances of `\n` to `\r\n`, resulting in annoyance with text files and data corruption with binary files.

## Expected behavior
`encfsctl cat` should output all decrypted data as-is. This is the behaviour of the Linux version.

## Steps to reproduce problem
1. Encrypt a file containing newlines `\n` (ASCII 0x0a)
2. Use `encfsctl cat` to decrypt the file.
3. All instances of `\n` are replaced with `\r\n`, including in existing `\r\n` sequences!

Not-at-all-robust workaround:

    encfsctl cat [dir] [file] | tail -c+17 | sed -b ":a;N;$!ba;s/\r\n/\n/g" > out.txt
                                ^ work around #42

**Comment by jetwhiz** [comment]
encfs4win needs to explicitly request to use binary mode output in this case (which isn't necessary on Linux).  The following patch (which will be included in 1.10.1-RC7) should fix this issue: 

[patch.txt](https://github.com/jetwhiz/encfs4win/files/297802/patch.txt)

**Comment by jetwhiz** [comment]
This should be fixed as of -RC7
