### ISSUE TITLE
encfsctl cat outputs debug information and prompts to stdout

### ISSUE THREAD

**Issue by RunasSudo** [jetwhiz/encfs4win#42]
# Environment
 * Windows version: Windows 7, wine
 * Processor architecture: x86, x64
 * Encfs4win version: 1.10.1-RC6
 * Dokan version (legacy, modern): modern

# Description 
`encfsctl cat` outputs debug information and prompts to stdout, along with the decrypted data.

## Expected behavior
`encfsctl cat` should output debug information and prompts to stderr, with only decrypted data printed to stdout. This is the behaviour of the Linux version.

## Steps to reproduce problem
1. Run `encfsctl -v cat [dir] [file] > out.txt`.
2. No output will be displayed at all, while all data (including debug messages and the `EncFS Password:` prompt) is stored in `out.txt`.

Not-at-all-robust workaround:

    encfsctl cat [dir] [file] | tail -c+17 > out.txt

**Comment by jetwhiz** [comment]
When you mention the LInux version, are you referring to the version from the official Linux repositories, or the version directly from https://github.com/vgough/encfs (the latest commit)?  

I'm thinking this is an issue due to easylogging++, which appears to support "To_Standard_Output" but not sending to standard error.  If that's the case, than the latest from vgough/encfs should also have this issue.

**Comment by jetwhiz** [comment]
I'm not sure if we can fix the "prompts to stdout" issue, since this is the correct behavior (the prompt goes to stdout as it should, but you're redirecting stdout to a file).  In this case, it is best to use -S to retrieve the password without prompts.

**Comment by RunasSudo** [comment]
I'm using encfs official release 1.8.1 on Arch Linux. Prompts are written to std**err**, so even if stdout is redirected, password prompts and debugging information are visible.

**Comment by jetwhiz** [comment]
Ok, I can fix the prompts (by sending them to stderr), but the issue of verbose debugging info going to stdout also exist in encfs upstream.  I'm going to open an issue upstream so this can be fixed at the source.

**Comment by jetwhiz** [comment]
This should be fixed as of -RC7
