### ISSUE TITLE
encfsctl cat crashes when output is piped, unless verbose mode is enabled

### ISSUE THREAD

**Issue by RunasSudo** [jetwhiz/encfs4win#43]
# Environment
 * Windows version: Windows 7, wine
 * Processor architecture: x86, x64
 * Encfs4win version: 1.10.1-RC6
 * Dokan version (legacy, modern): modern

# Description 
`encfsctl cat` crashes after output is piped, either to file or to another program, *unless* verbose mode is enabled.

## Expected behavior
`encfsctl cat` should not crash.

## Steps to reproduce problem
1. Run `encfsctl cat [dir] [file] > out.txt` or `encfsctl cat [dir] [file] | some-command`.
2. After inputting the password, encfsctl crashes, though the contents of the file are piped successfully.
3. The error does not occur if `encfsctl cat -v` is run instead.

# Relevant logs

No errors are written to logs when verbose mode is disabled. The issue does not occur when verbose mode is enabled.

**Comment by jetwhiz** [comment]
This was somewhat related to issue #42.  The following patch (which will be in RC7) should fix this: 

[patch.txt](https://github.com/jetwhiz/encfs4win/files/298858/patch.txt)

**Comment by jetwhiz** [comment]
This should be fixed as of -RC7
