### ISSUE TITLE
What is the correct way to unmount a system which has been spawned as daemon?

### ISSUE THREAD

**Issue by imperative** [jetwhiz/encfs4win#46]
In Linux, we have `unmount`.
In this version I haven't been able to find, either in documentation or command line help, what is the correct way to unmount a previously mounted system? Also to view a list of mounted systems? Maybe this should be included as a command-line function.

**Comment by jetwhiz** [comment]
Hi @imperative 

Right now the only option is to do this via Dokany: 

````cmd 
dokanctl.exe /u Z:
````

After the relevant pull request is completed upstream (vgough/encfs/pull/167), there will also be the option for: 

````cmd
encfs.exe --unmount Z:
````

**Comment by benrubson** [comment]
https://github.com/vgough/encfs/pull/474 will add `-u / --unmount`.

**Comment by jetwhiz** [comment]
That's great news ... thanks @benrubson !

**Comment by jetwhiz** [comment]
This will be fixed with the v1.11.0 release, since this feature has been implemented upstream in encfs.
