### ISSUE TITLE
problems with lock an moinmoin

### ISSUE THREAD

**Issue by Analitico** [jetwhiz/encfs4win#48]
Win10 x64
1.10.1-RC7

I'm having problems with MoinMoin and locking, sometimes cannot adquire lock, 

There is any way to disable locks ?

Thnak you

**Comment by jetwhiz** [comment]
@Analitico -- that's for reporting this behavior!  Just to make sure I understand correctly, does that mean that MoinMoin successfully acquires locks sometimes, but fails under certain circumstances?  

Do you notice any pattern on when the lock acquisition fails, so that I can try to reproduce this issue?

**Comment by Analitico** [comment]
After the first lock error it gives error in all de pages, the first error is fast also, one edit or one new page, trace:
`    application_iter = app(environ, start_response)
  File "P:\moin\MoinMoin\support\werkzeug\wsgi.py", line 411, in __call__
    return self.app(environ, start_response)
  File "P:\moin\MoinMoin\wsgiapp.py", line 282, in __call__
    response = run(context)
  File "P:\moin\MoinMoin\wsgiapp.py", line 88, in run
    response = dispatch(request, context, action_name)
  File "P:\moin\MoinMoin\wsgiapp.py", line 136, in dispatch
    response = handle_action(context, pagename, action_name)
  File "P:\moin\MoinMoin\wsgiapp.py", line 195, in handle_action
    handler(context.page.page_name, context)
  File "P:\moin\MoinMoin\action\edit.py", line 166, in execute
    savemsg = pg.saveText(savetext, rev, trivial=trivial, comment=comment)
  File "P:\moin\MoinMoin\PageEditor.py", line 1137, in saveText
    mtime_usecs, rev = self._write_file(newtext, action, comment, extra, deleted=deleted)
  File "P:\moin\MoinMoin\PageEditor.py", line 919, in _write_file
    self.setConflict(wikiutil.containsConflictMarker(text))
  File "P:\moin\MoinMoin\Page.py", line 1674, in setConflict
    cache.remove()
  File "P:\moin\MoinMoin\caching.py", line 290, in remove
    self.lock('w')
  File "P:\moin\MoinMoin\caching.py", line 157, in lock
    raise CacheError(err)
CacheError: Can't acquire w lock in P:\moin\wiki\data\pages\Organiza(c3a7c3a3)oPessoal\cache\__lock__`


I'm using the internal http server of MoinMoin,

**Comment by jetwhiz** [comment]
@Analitico -- can you provide some debug data from encfs4win that might help determine where the problem lies?  Try running encfs.exe with the "-v" verbose flag: 

````cmd
encfs.exe -v   CRYPT_PATH   MOUNT_POINT
````

If you are running in background mode, the logs should be available in your TEMP folder.  If in foreground mode (-f flag) then the logs will output to the terminal.

**Comment by Analitico** [comment]
with -f -v there isn't any error, I believe is because of the delay, the encfs folder is shared with dropbox, if I stop dropbox I don't get the errors.

**Comment by jetwhiz** [comment]
@Analitico  -- can you test and see if this problem also exists in [1.10.1-RC6](https://github.com/jetwhiz/encfs4win/releases/tag/1.10.1-RC6)?

**Comment by Analitico** [comment]
@jetwhiz 
With  1.10.1-RC6 MoinMoin doesn't give errors even with dropbox working

**Comment by jetwhiz** [comment]
@Analitico --  I am going to remove the locking mechanism from encfs to fix this issue until I have more time to ensure the implementation doesn't cause any issues.

**Comment by Analitico** [comment]
@jetwhiz, thank you
