### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Driim** [jetwhiz/encfs4win#5]
I trying to build project on Windows 8.1 VS 2015 and get fuse_win.h(61) error C2011:  : 'struct' type redefinition.
Problem solved when i defined HAVE_STRUCT_TIMESPEC

**Comment by jetwhiz** [comment]
Hi Driim, 

Thanks for reporting this bug!  Can you apply the following patch and see if it resolves the issue?  Also, please remember to remove the definition of HAVE_STRUCT_TIMESPEC from your project before testing this patch. 

[patch.txt](https://github.com/jetwhiz/encfs4win/files/110079/patch.txt)

It basically adds these lines of code to unistd.h: 

```CPP
/* VS2015+ complies with C11 and defines timespec */
#if defined(_MSC_VER) && _MSC_VER >= 1900 && !defined(_CRT_NO_TIME_T)
#define HAVE_STRUCT_TIMESPEC 1
#define _TIMESPEC_DEFINED
#endif
```

**Comment by Driim** [comment]
No, it did not help. if move this lines to encfs.h just before #include "fuse.h" it works.

**Comment by jetwhiz** [comment]
Great -- I have included these changes to the latest commit to encfs4win.  If you notice that a problem still persists with the latest version please let me know!
