### ISSUE TITLE
Must wait some time after reboot to mount encfs drive

### ISSUE THREAD

**Issue by Analitico** [jetwhiz/encfs4win#50]
Win 10 x64
1.10.1-RC6
1.10.1-RC7
modern

Can't mount encfs volume immediately after reboot, I must wait some time (more or less 3 minutes), maybe some delay in loading the dokan service ?

log:

```
Dokan: debug mode on
Dokan: use stderr
device opened
DokanBroadcastLink: Begin SHChangeNotify
DokanBroadcastLink: SHChangeNotify done
mounted: p: -> \Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}
Mounted
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 2
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 2
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 2
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 2
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 2
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 2
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 2
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 2
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 2
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 2
Unmount

unload
send global release for p:
DokanBroadcastLink: Begin SHChangeNotify
DokanBroadcastLink: SHChangeNotify done
```

**Comment by jetwhiz** [comment]
Hi @Analitico -- can you try copying the "dokanfuse1.dll" file from the Dokan Program Files folder to the encfs folder and see if this helps at all?  Dokany's system driver should be marked as a SYSTEM_START service, so it should be loading pretty early on.

**Comment by Analitico** [comment]
@jetwhiz, 
I copied all the dll's in x86 folder to the encfs folder, and I changed the start from SYSTEM to BOOT, same problem. To me is not a big deal of a problem, but I believed is better to report the issue

**Comment by jetwhiz** [comment]
@Analitico -- if you can recreate this issue with the fuse_mirror sample (located at \Dokan\Dokan Library-1.0.0\sample\fuse_mirror\mirror.exe), then this is likely to be an issue with Dokany.  In that case, it might be good to report this to them so that they can put the proper timeouts or checks in place to prevent this from being an issue.  

Do you know if this problem exists for you in the fuse_mirror?

**Comment by Analitico** [comment]
@jetwhiz, mirror.exe needs cygwin, I dont have that instaled

**Comment by Analitico** [comment]
@jetwhiz 
1.10.1-RC8 Solved the issue

**Comment by jetwhiz** [comment]
Great!  Let me know if anything similar pops up!
