### ISSUE TITLE
Add notice to the document that mount point should be a drive

### ISSUE THREAD

**Issue by korokoro** [jetwhiz/encfs4win#51]
Hi,

The documentation of the older encfs4win[1] describes the following problem:

> launch "encfs &lt;crypt_dir> &lt;plain_dir>" where crypt_dir is crypted directory while plain_dir is the directory where you can access not crypted files.
> **NOTE: Windows 7 users should use a drive (like "X:") as plain_dir to avoid case sensitive problems which results in file/folder not found problems.** 

[1] http://members.ferrara.linux.it/freddy77/encfs.html

I found that this is still true in the current version of encfs4win.  (I tested with 1.10.1-RC7 on Win 7/10 32bit)
I would suggest to add notice about this problem to README.  It should be helpful for new users.

I would also suggest to make encfs show a warning if plain_dir is not a drive (or make encfs refuse any plain_dir which is not a drive.)

Thanks,

**Comment by jetwhiz** [comment]
Hi @korokoro -- We're trying to figure out a way to fix this issue so that it isn't necessary to mount to a drive letter anymore, and have a bug report out on Dokany regarding this.  

If we can't fix this before the next release, however, then we will definitely add this to the documentation and program!

**Comment by korokoro** [comment]
@jetwhiz, thank you for your quick reply.
I'm happy to hear that and I hope the problem could be fixed. :D

**Comment by Owyn** [comment]
Is there a fix possible for this? 😿

**Comment by jetwhiz** [comment]
@Owyn -- the only quick-fix I've been able to think of would be to have an option to force all directory/file names to be all uppercase.  Such an option would break compatability with encfs upstream, though, and I don't think that the encfs project will be willing to implement this type of quick fix in the main project. 

As of right now it is still a mystery why Windows/Dokany converts everything to uppercase when directory junctions are used.

**Comment by Owyn** [comment]
> why Windows/Dokany converts everything to uppercase when directory junctions are used.

it seems I cannot reproduce the problem, all 800 gb and 200,000 of files of mixed uppercase\undercase are OK for me, all found, all have their own names.

**Comment by jetwhiz** [comment]
@Owyn -- if you're using Block32 filename encoding, then this issue might not exist with --reverse mode enabled.
