### ISSUE TITLE
Multiple issues with setting up an encrypted folder

### ISSUE THREAD

**Issue by Zero3** [jetwhiz/encfs4win#52]
# Environment
 * Windows version: Windows 7
 * Processor architecture: 64-bit
 * Encfs4win version: 1.10.1-RC8
 * Dokan version (legacy, modern): modern

# Description 

The setup wizard for creating an encrypted folder acts weirdly at this point:

````
C:\Program Files (x86)\encfs>encfs D:\Enc D:\Dec
The directory "D:\Enc/" does not exist. Should it be created? (y,n) y
The directory "D:\Dec" does not exist. Should it be created? (y,n) y
Creating new encrypted volume.
Please choose from one of the following options:
 enter "x" for expert configuration mode,
 enter "p" for pre-configured paranoia mode,
 anything else, or an empty line will select standard mode.
?>
````

If you wait for ~10 seconds at this point, it appears like encfs4win closes itself and you get thrown back to the command line:

````
C:\Program Files (x86)\encfs>
````

But if you try to type in a command, you will see that encfs4win is still in control:

````
C:\Program Files (x86)\encfs>echo Hello

Standard configuration selected.

Configuration finished.  The filesystem to be created has
the following properties:
Filesystem cipher: "ssl/aes", version 3:0:2
Filename encoding: "nameio/block32", version 4:0:2
Key Size: 192 bits
Block Size: 1024 bytes
Each file contains 8 byte header with unique IV data.
Filenames encoded using IV chaining mode.
File holes passed through to ciphertext.

Now you will need to enter a password for your filesystem.
You will need to remember this password, as there is absolutely
no recovery mechanism.  However, the password can be changed
later using encfsctl.

New Encfs Password:
````

Additionally, CTRL + C does not work as expected, and needs to be used multiple times to completely quit encfs4win.

I noticed that encfs4win now launches itself as a child process at some point in the wizard. Maybe this is the cause of these weird issues?

**Comment by jetwhiz** [comment]
@Zero3 -- can you try this with a clean install of both encfs and Dokany?  This seems to be working fine on my machines, and the child process has been implemented since RC6 (it wasn't added recently).

**Comment by Zero3** [comment]
@jetwhiz This was a clean install on a new machine :(. I don't think I tested this since before RC6 actually, so you probably can't rule that out. Anything I can do to help debug this?

**Comment by jetwhiz** [comment]
@Zero3 -- ah, I see the issue.  Right now the parent will wait for up to 10 seconds (polling every 200 ms, checking to see if the drive is mounted yet) before exiting.  
 
I will change it so the parent waits indefinitely, and only exits if either the drive is mounted or there is a problem.  

Can you try with this patch to see if it fixes the issue?  

[patch.txt](https://github.com/jetwhiz/encfs4win/files/399585/patch.txt)

**Comment by Zero3** [comment]
@jetwhiz Good to hear! Maybe you could compile a verison for me? I never tried compiling encfs4win myself. I'm curious as to why you see different results than me though. You should be able to test/verify your solution for this issue just as well as me.

**Comment by jetwhiz** [comment]
@Zero3 -- I have included this fix for RC9, so you can download the preview of it here: 

https://dl.dropboxusercontent.com/u/50973674/encfs-installer.exe

Note that this version has a new way of computing inode numbers for files, so if you used per-file IVs then an old encfs filesystem might not be compatible with this version (so you might have to re-encrypt).   Also, NTFS is now required to use per-file initialization vectors, since FAT32 does not have such a feature.

**Comment by jetwhiz** [comment]
My mistake -- you should not have to re-encrypt, since this issue affects reverse encryption only (with per-file IV).  This has been fixed as of RC9.
