### ISSUE TITLE
Wrong filesize and date

### ISSUE THREAD

**Issue by Analitico** [jetwhiz/encfs4win#54]
Win10 x64
1.10.1-RC8 modern

wrong file sizes and dates, see attachment 

![capture](https://cloud.githubusercontent.com/assets/20475784/17368171/d33c3332-598a-11e6-9099-375bfae5cbcc.JPG)

**Comment by Analitico** [comment]
reinstalling dokany RC4 fixed the problem

**Comment by jetwhiz** [comment]
@Analitico -- yeah I was going to mention that this was fixed with Dokany RC4, so there was probably just an issue upgrading Dokany.
