### ISSUE TITLE
Windows installer freezes

### ISSUE THREAD

**Issue by stefanmohl** [jetwhiz/encfs4win#58]
# Environment
- Windows version: Windows 10
- Processor architecture: x64
- Encfs4win version: 1.10.1-RC9
- Dokan version (legacy, modern): -
# Description

Windows installer freezes upon launch
## Expected behavior vs. actual behavior

It is expected that the installation will proceed. Instead the installer spawns a child and a grandchild, whereupon it no more activity is noticeable. None of the three installer processes can be killed (a second kill attempt reports "Access is denied"). My first attempt was with an installed Dokan 0.8, I uninstalled Dokan 0.8, rebooted and retried, but with the same result.
## Steps to reproduce problem
1. Double click the installer
# Relevant logs

If I can get you some logs, I will be happy to do so, but I need to know where to get them from.

Attach any relevant log files that can help to debug your issue (be sure to use the -v option for verbose logs).

**Comment by jetwhiz** [comment]
Hi @stefanmohl -- thank you for your bug report!   Are you able to successfully install Dokany v1.0.0-RC4 on your machine (https://github.com/dokan-dev/dokany/releases/tag/v1.0.0-RC4)?  

This seems like it might be an issue related to the Dokany installer (or installation process).

**Comment by stefanmohl** [comment]
Yes, I was able to install Dokan-v1.0.0-RC4. However, I also happened to upgrade from Windows 10 to Windows 10 Anniversary Edition between the two install attempts, so that might have had some influence on things...

**Comment by jetwhiz** [comment]
Does the encfs4win installation succeed if you uncheck the box to install Dokan-v1.0 (since you have manually installed it yourself)?

**Comment by jetwhiz** [comment]
@stefanmohl -- do you still experience this issue with the latest version of encfs4win?  
https://github.com/jetwhiz/encfs4win/releases/tag/v1.10.1-RC11

**Comment by stefanmohl** [comment]
I am sorry, I have gone a different route, so I haven't tested it properly.

**Comment by jetwhiz** [comment]
Since this bug involved Dokany 0.8 (Dokany stable is now 1.0) I'm going to close this issue (since it was likely related to that).  If someone else experiences this same issue then I will re-open it, though.
