### ISSUE TITLE
request: mount as read-only

### ISSUE THREAD

**Issue by Owyn** [jetwhiz/encfs4win#65]
It'd be very useful for --reverse mode in cloud usage scenario cuz those things always seem to mess files up 

It should be very easy to implement as a flag then just few checks in write\delete\create for file\dir functions

many encryption softwares has this option, truecrypt for example could mount as read-only

**Comment by jetwhiz** [comment]
Hi @Owyn -- the file system should be read only in reverse mode unless you have "per-file initialization vectors" disabled (as per https://github.com/vgough/encfs/commit/cd89e60ff26977d9b946bbcb6be15a754b0904c7 upstream) 

Is reverse mode still writable for you even with per-file IV enabled?

**Comment by Owyn** [comment]
Yes, I have it disabled cuz I have null encryption for filenames (cuz I have many sub-subfolders)

**Comment by jetwhiz** [comment]
It might be a good addition to have a --readonly option for mounting in general!  I will see what I can do and work with the encfs project upstream to see if they like the idea.

**Comment by leochou0729** [comment]
Hello, 
On MacOS, I can use "-- -o rdonly" option to mount encfs drive as read only, but it doesn't have any effect on Windows. Adding a "--readonly" option in source code like --reverse also didn't work. I have no idea what's the problem. Can anyone help? @jetwhiz

**Comment by jetwhiz** [comment]
Hi @leochou0729 

It is possible that both the readonly option (from --reverse) and the -r rdonly FUSE flag need to be set for this to work.  Can you tell if this helps the issue?

**Comment by leochou0729** [comment]
@jetwhiz Sorry for the late reply. I set both flags, but it doesn't work. The drive is still writable.

**Comment by leochou0729** [comment]
I can use "-o rdonly" with OSXFUSE to make encfs drive non-writable on MacOS. I'm not sure if it is a bug in Dokan.

**Comment by jetwhiz** [comment]
It's possible that Dokan doesn't support this, but I haven't been able to confirm for certain.  When using the Dokan sample fuse program (sample\fuse_mirror\mirror.exe), rdonly isn't listed as an option, and when you supply it the folder is not read only.  Can you confirm this on your side?

**Comment by leochou0729** [comment]
Hi @jetwhiz , I've tried mirror.exe. With /w option, I can mount the virtual drive as read only.

**Comment by leochou0729** [comment]
I noticed fuse mirror doesn't support read-only mode but mirror has a /w option.

**Comment by jetwhiz** [comment]
Hi @leochou0729 -- the mirror should work correctly since it is Dokany itself, but I have not yet found a way to make the FUSE portion of Dokany (which we're using) work in read-only mode.  I will have to check with @Liryna to see for sure.

**Comment by leochou0729** [comment]
I just made a PR. Thanks, @jetwhiz.

**Comment by jetwhiz** [comment]
Hi @leochou0729 

It appears that read-only mode is working for me now with the latest encfs4win ... can you confirm?  You can enable it by using the Dokany read-only flag: "-o -r", for example: 

`encfs.exe C:/path/to/my/folder  Z: -o -r`
