### ISSUE TITLE
Missing dll's

### ISSUE THREAD

**Issue by majkinetor** [jetwhiz/encfs4win#66]
# Environment
 * Windows version: Windows Server 2012 R2
 * Processor architecture:  64b
 * Encfs4win version: 1.10.1-RC10

```
---------------------------
encfsw.exe - System Error
---------------------------
The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 

---------------------------
encfs.exe - System Error
---------------------------
The program can't start because dokanfuse1.dll is missing from your computer. Try reinstalling the program to fix this problem. 
```

This shouldn't happen based on:

> The installer contains everything needed to run encfs on Windows, including the encfs executables, OpenSSL libraries, and all necessary MS Visual C++ libraries. It will also automatically install the Dokan library (if it is not already installed).

**Comment by majkinetor** [comment]
Also

Running Dokan_x64.msi produces:

`Universal runtime is not installed, kb2999226`

**Comment by jetwhiz** [comment]
Hi @majkinetor -- thanks for the bug report!  This looks like it's probably an issue with the Dokany installer with Windows Server 2012 R2.  

Can you try installing the Universal C Runtime (https://support.microsoft.com/en-us/kb/2999226) and then re-installing to see if that fixes the issue?

**Comment by majkinetor** [comment]
Yes, I am doing that now in my test environment. 

I am doing this as a test for chocolatey package: https://chocolatey.org/packages/encfs4win

Currently it is outdated and I testing new updater that will follow your release schedule up to a few hours - you can mention it in install section when I finish.

**Comment by majkinetor** [comment]
Yeah, it works.

Notes:
- Uninstaller doesn't remove encfsw if it runs. Probably the best to kill it. Choco package does that.
- Installing before restarting system fails, dokany is the problem again. So this can't be done in a single run by chocolatey if the runtime is not present.

[details](https://github.com/chocolatey/chocolatey-coreteampackages/pull/401)

**Comment by jetwhiz** [comment]
Great, thank you @majkinetor !   I will update our installation section to reflect this addition.  

I will also open a bug report in order to improve the installer/uninstaller with your suggestions.
