### ISSUE TITLE
Improve installer/uninstaller

### ISSUE THREAD

**Issue by jetwhiz** [jetwhiz/encfs4win#68]
## Installer

Add encfs to Add/Remove Programs
Detect if encfs already installed and recommend remove-install (or similar) 
Provide nodeps version of installer (no Dokany or redistributables)? 

## Uninstaller

Terminate/warn any running encfs programs (which would cause failure of total uninstall)

**Comment by thedewi** [comment]
Another possible enhancement: would it be worth adding a start menu shortcut for ```encfsw.exe```?

**Comment by jetwhiz** [comment]
@thedewi -- that could be useful, and also asking if the user wants it auto-started on boot.

**Comment by jetwhiz** [comment]
The next version of the installer will have most of these features, except for the uninstaller detecting if encfs is currently running.  I'll try to get this working before the 1.10.1 release.

**Comment by benrubson** [comment]
So as stated in #100, I noticed that Dokany needs VC redist of 2017 (DokanSetup_redist.exe includes it).
Current version of EncFS4win brings 2 additional versions of VC (btw are there here for Dokany, or for EncFS4win ?).
If EncFS4win needs VC, perhaps it could be nice to use the version Dokany includes ?
Thus less VC to redistribute and to install (only one, already in Dokany), smaller packages etc...
Many thanks 👍
