### ISSUE TITLE
Can't unmount drive from command line

### ISSUE THREAD

**Issue by heX16** [jetwhiz/encfs4win#70]
# Environment
 * Windows version: 10
 * Processor architecture: x64
 * Encfs4win version: v1.10.1-RC10
 * Dokan version (legacy, modern): Dokany v1.0.1 (stable)

# Description 
Mount use command "encfs.exe D:\crypt\encfs_test q:"
And how unmount it? Try command "encfs.exe -u q:", "dokanctl.exe -u q:" and other.
See man for encfs.exe, dokanctl.exe, encfsctl.exe, encfsw.exe.
Read https://github.com/jetwhiz/encfs4win/blob/master/encfs/encfs.pod (write "use fusermount" - but its linux command) and https://github.com/jetwhiz/encfs4win/blob/master/DESIGN.md.
See source encfsw.exe - maingui.cpp use DokanUnmount function and not support command line parameters.
Find in google and repository issues - empty.
Nowhere command for unmount drive.
Kill task "encfs.exe --forked  D:\crypt\encfs_test q:" - drive present in system (but not work)!
How unmount? =)

## Steps to reproduce problem
1. mount drive from command line
2. try remove drive from system

**Comment by jetwhiz** [comment]
Hi @heX16, thank you for the report!  An --unmount option has already been created for encfs4win, but I am waiting for the change to be included in the upstream encfs project: https://github.com/vgough/encfs/pull/167.  

In the meantime, you should be able to unmount with ````dokanctl.exe /u q ````

**Comment by jetwhiz** [comment]
I'm going to merge this issue with https://github.com/jetwhiz/encfs4win/issues/46 since they are very similar.
