### ISSUE TITLE
encfs.exe abnormally high cpu usage

### ISSUE THREAD

**Issue by Rawing** [jetwhiz/encfs4win#73]
# Environment
 * Windows version: Windows 10 Pro 10.0.14393
 * Processor architecture: Processor	AMD FX(tm)-6300 Six-Core Processor, 3500 Mhz, 3 Core(s), 3 Logical Processor(s)
 * Encfs4win version: 1.10.1-RC10
 * Dokan version (legacy, modern): Dokany 740

# Description 
I've used encfs4win for a few months now and I've never had any problems. But since a few days ago, after I mount my encrypted folder, the CPU usage of the encfs.exe process is abnormally high (anywhere between 30% and 90%), even while I'm not accessing any files/folders on the mounted drive. Unmounting the folder (through the encfsw application) ends the encfs.exe process without any problems, as expected. The problem persisted after I upgraded to the latest version.

additional info:
*) Mounting to a different location (Y: instead of X:) makes no difference.
*) Creating and mounting a new encrypted folder works as it should, with cpu usage being at 0%. Perhaps the issue is related to the number of files/folders in the encrypted directory?
*) I thought perhaps my antivirus is trying to scan the mounted drive, but the issue persisted after I disabled my antivirus.

Update:
The issue only occurs once I open Windows Explorer. If I uncheck "open drive after mounting" in the encfsw preferences, the cpu usage stays at 0% after mounting, until I open Windows Explorer. So I guess this isn't an issue with encfs4win, but rather Windows Explorer.

**Comment by jetwhiz** [comment]
@Rawing -- thank you for the report!  does this only happen when using encfsw, or also when you run encfs4win via the command line?

**Comment by Rawing** [comment]
It's been a while since then. I no longer have the same setup, so I can't actually confirm if it makes a difference. But I have a suspicion that the problem was related to having file names with non-ascii characters. I'm pretty sure the problem occured after I downloaded some files with japanese names. That would also explain why an empty drive didn't cause any problems.

**Comment by Rawing** [comment]
Like I said in my previous comment, I have reinstalled Windows and Encfs4Win in the meantime. But I can now mount the very same encrypted directory without experiencing any unusual CPU usage. It looks like an update in encfs4win (or maybe dokany) has fixed the problem. (For future reference, I'm now using encfs4win version 1.10.1-RC11.)

**Comment by jetwhiz** [comment]
Great news, thank you for the update, @Rawing!  I will assume this is fixed in the latest version then.
