### ISSUE TITLE
Unclear download file names and differences (what is legacy and why is it listed first?)

### ISSUE THREAD

**Issue by jumper444** [jetwhiz/encfs4win#86]
I arrive at the site ready to try/use encfs4win.

I proceed to download the file and am confronted by a simple yet confounding problem.  There are two files "legacy" and one without that word.  The legacy file is listed FIRST, ostensibly implying that is what I want generally.  After the legacy file is a file without the word legacy.  It's twice as big.  Um..ok...so then I read the page (and a few other pages) and nothing tells me what the difference is and which one I want (or don't want) and why.

The only text of any relevance I can find is:
"Dokan library - Handles FUSE portion of software. You can use either legacy (e.g., v0.7.4) or latest (v1.0)."
But this still doesn't tell me (for sure) that the 'legacy' build is a legacy "Dokan Library" (pretend I don't know what that is).  Or why I want one vs the other.

My suggestion is to place a sentence or two near the downloads('releases') page explaining the difference in the two packages. (the "dokan library" sentence above, which itself isn't that useful, was not on the releases page with the download links)...and then ideally explaining WHY the two packages exist beyond just saying (if this is true) that "one uses old Dokan" since I don't know what ramifications it has to me as a user.  Does it mean certain issues with various versions of windows? Bugs that need to remain to handle certain software? Etc.

I'm going to just download the non-legacy version at this point, but it doesn't make me comfortable that I don't know the difference as computer person or at least have a bit of information to go on as to why both or there and why the legacy is listed first.

**Comment by jumper444** [comment]
Oh...and the releases page says:
"..v1.10.1-RC11..
This version is based on the following software:
    encfs v1.9.1 (stable)
    Dokany v1.0.2 (stable)
    tinyxml2 v.3.0.0..."

And then BOTH the 'legacy' and non-legacy builds are listed below this statement.  So it's implying the RC11 'legacy' and non BOTH have "Dokany v1.0.2" by the way the page is printed yet my (only other) piece of info seems to imply 'legacy' build has older Dokany.  So now I'm back to zero info about the difference in the two.

**Comment by jetwhiz** [comment]
That's a great point, @jumper444!  I'll see if there is a way I can rearrange to have the modern release listed first from now on.  

I have fixed the issue where the release said it included Dokany v1.0.2 (by including both Dokany v1.0.2 and Dokan v0.7.4).  Also I have added a brief description about the differences between modern vs. legacy Dokany to help users choose the most appropriate one.  

Please let me know if you have any other suggestions on how to improve this!

**Comment by Rondom** [comment]
What is the use case of the legacy-version? I have a hard time imagining a case where one would need to use it.

**Comment by jetwhiz** [comment]
@Rondom -- I think the legacy version will be less-and-less needed as the modern Dokany version matures more.  We originally introduced it while Dokany v1.0 was still giving blue screens often (so at least people had something they knew was stable that could be used).  

We will probably keep support for the legacy version in case people want to build against it themselves for whatever reason, but at some point we can drop the built release of encfs4win-legacy.exe.
