### ISSUE TITLE
Avast Reports as Virus

### ISSUE THREAD

**Issue by rcsnow** [jetwhiz/encfs4win#90]
# Environment
 * Windows version:  10 Version 1607 (OS Build 14393.1593
 * Processor architecture: x64
 * Encfs4win version: v1.10.1-RC12
 * Dokan version (legacy, modern): 
Dokany v1.0.3 (modern)

# Description 
Avast anti-virus is reporting this as malware.  I reported it as false positive but it keeps putting the app in quarantine.  It flags the file before I can finish downloading it . On Virus Total there are quite a few anti-virus applications flagging this as malware.

## Expected behavior vs. actual behavior 
Is there anything else that can be done to stop it being flagged as malware?

## Steps to reproduce problem
1. Install Avast anti-virus
2. download and andinstall encfs4win

# Relevant logs

Attach any relevant log files that can help to debug your issue (be sure to use the -v option for verbose logs).

**Comment by jetwhiz** [comment]
Unfortunately this is a common issue with the NSIS installer software that we're using to create the installer.  Eventually we can switch to a more advanced installer, but for now all that can be done is to report the file as a false positive and have the company inspect it so the issue can be corrected.
