### ISSUE TITLE
encfs handles umlauts (ä,ö,ü) incorrectly

### ISSUE THREAD

**Issue by mazimmer** [jetwhiz/encfs4win#92]
# Environment
 * Windows version: Win7
 * Processor architecture: x86
 * Encfs4win version: 1.10.1-RC11
 * Dokan version (legacy, modern): modern

# Description 
When trying to use a directory containing a German umlaut, the umlaut is changed to another character and the directory not found. Some umlauts (ö,ü) cause encfs.exe to hang.

## Steps to reproduce problem
* Create directory containing umlaut, eg. "ä"
* try to create encfs volume in this directory
* get error that a different directory doesn't exist

Example:
C:\Users\MBRANE\Test>f:\src\encfs.exe c:/Users/MBRANE/Test/ä x:
The directory "c:/Users/MBRANE/Test/õ/" does not exist. Should it be created? (y,n) n

**Comment by jetwhiz** [comment]
Thanks for the report, @mazimmer !

I wonder if this is related to issue https://github.com/jetwhiz/encfs4win/issues/55 in some way.  

Does this problem only occur for you if the mounting directory has an umlaut, or also if directories and files within the encfs container have umlauts?

**Comment by mazimmer** [comment]
Umlauts within the container don't seem to be a problem - just tried re-mounting a container with such a folder, no issue.

So it only seems to occur with mounting umlaut-directories.
