### ISSUE TITLE
Cannot save Excel files to mounted encfs volume

### ISSUE THREAD

**Issue by hrunting** [jetwhiz/encfs4win#93]
# Environment
 * Windows version: Windows 10 Pro
 * Processor architecture: 64-bit
 * Encfs4win version: 1.10.1-RC12
 * Dokan version (legacy, modern): modern

# Description 
I mount my encfs volume to a drive letter. Then I open an Excel file from the encfs volume in Excel 2016. I then immediately click save. Excel hangs and then reports that the file cannot be saved. It then saves the changes to a temporary file on the volume. The help error says that antivirus can cause this problem. The only antivirus I have is Windows Defender. I would previously mount this volume using Boxcryptor Classic 1.7, and I had no issues saving.

![excel error](https://user-images.githubusercontent.com/260933/33717189-9b979fc2-db1e-11e7-9b5c-c98737fc8756.png)

## Expected behavior vs. actual behavior 
When I click Save in Excel, the file saves like it would save on any non-encfs volume.

## Steps to reproduce problem
1. Mount encfs volume to drive letter
2. Open Excel file from mounted drive
3. Save Excel file

# Relevant logs

Attach any relevant log files that can help to debug your issue (be sure to use the -v option for verbose logs).

**Comment by hrunting** [comment]
I noticed that my installed version of Dokan was 1.0.2.x -- according to the Windows 10 Apps control panel. I downloaded and installed the 1.1.0.x of Dokan and the problem has gone away. The 1.0.2.x version was what was installed by the encfs release I downloaded (even though the docs say that it should have been 1.0.3.x). Maybe that is an Apps control panel display issue with Dokan, but regardless, the new 1.1.0.x version does not appear to have an issues saving files.

**Comment by jetwhiz** [comment]
Hi @hrunting -- thank you for bringing this to my attention!  This was a known issue in Dokany 1.0, but it looks like they have recently fixed it with v1.1 (see https://github.com/dokan-dev/dokany/issues/611).  

I will try switching over to v1.1 with the next release candidate of encfs4win.
