### ISSUE TITLE
Reverse mode not showing all files ?

### ISSUE THREAD

**Issue by benrubson** [jetwhiz/encfs4win#98]
# Environment
 * Windows version: 7 SP1
 * Processor architecture: 64 bits
 * Encfs4win version: v1.10.1-RC12
 * Dokan version (legacy, modern): built-in modern, and last modern (1.1.0.2000)

# Description 
Using reverse mode does not show all files / directories, even if command is run with administrator rights.

## Expected behavior vs. actual behavior 
All directories and files should be shown in reverse mode.

## Steps to reproduce problem
1. Start `cmd` with administrator rights
2. `encfs --reverse "C:\Users" X:` (use Null ciphername encryption)
3. Browse X: and compare to C:\Users

# Relevant logs
```
[DirNode.cpp:667] created FileNode for C:\Users/Default User
[encfs.cpp:129] op: getattr : C:\Users/Default User
[default] [Usr@VMSEVEN] [int __thiscall encfs::RawFileIO::getAttr(struct stat64_cygwin *) const] [RawFileIO.cpp:169] get
Attr error on C:\Users/Default User: Permission denied
[default] [Usr@VMSEVEN] [int __cdecl encfs::withFileNode(const char *,const char *,struct fuse_file_info *,class std::fu
nction<int __cdecl(class encfs::FileNode *)>)] [encfs.cpp:146] op: getattr error: Permission denied
```

# Investigation
Going further, there are some symbolic links in C:\Users, as well as in other directories where I can reproduce the issue. Sounds like as soon as a symlink is encountered, dir listing stops.
Could we then simply ignore symlinks in reverse mode (until they are supported by Dokany) ?

Thank you 👍

**Comment by benrubson** [comment]
I'm pretty sure https://github.com/vgough/encfs/pull/356, which is encfs 1.9.4, would solve this issue 👍

**Comment by benrubson** [comment]
I think https://github.com/benrubson/encfs/commit/10c0ddf0deeee81af0e5d60ab0b47890b66b5e59 should correct the issue.
@jetwhiz could it be possible to have a compiled version of encfs4win including this tiny patch, so that I can test if bug is corrected, and then submit this patch to upstream encfs ?
Many thx 👍

**Comment by benrubson** [comment]
I tried to compile it myself using Visual Studio Community 2017 (my first time !) but it failed with an error MSB4062 I did not manage to get ride of...

**Comment by jetwhiz** [comment]
Hi @benrubson -- it looks like the patch doesn't get rid of it on the Windows side -- I think the error is occurring in the getAttr portion of the code: 

````cmd
2018-03-11 21:44:01,137 VER [encfs.cpp:129] op: getattr : C:\Users/Default/AppData
2018-03-11 21:44:01,152 VER [DirNode.cpp:675] created FileNode for C:\Users/Default/Application Data
2018-03-11 21:44:01,168 VER [encfs.cpp:129] op: getattr : C:\Users/Default/Application Data
2018-03-11 21:44:01,184 DEBUG [default] [jetwhiz@QUAD7] [int __thiscall encfs::RawFileIO::getAttr(struct stat64_cygwin *) const] [RawFileIO.cpp:169] g
etAttr error on C:\Users/Default/Application Data: Permission denied
2018-03-11 21:44:01,215 DEBUG [default] [jetwhiz@QUAD7] [int __cdecl encfs::withFileNode(const char *,const char *,struct fuse_file_info *,class std::
function<int __cdecl(class encfs::FileNode *)>)] [encfs.cpp:146] op: getattr error: Permission denied
2018-03-11 21:44:01,262 VER [DirNode.cpp:675] created FileNode for C:\Users/
2018-03-11 21:44:01,277 VER [encfs.cpp:129] op: getattr : C:\Users/
2018-03-11 21:44:01,277 VER [DirNode.cpp:675] op: getattr : C:\Users/created FileNode for C:\Users/Default
````

I've included the patched encfs.exe here (zipped up so github will let it be uploaded): 
[encfs.zip](https://github.com/jetwhiz/encfs4win/files/1800863/encfs.zip)

**Comment by benrubson** [comment]
Thank you very much @jetwhiz 👍 
I gave a try to your patched version, and unfortunately it does not correct the issue.
Certainly that readdir() does not set errno as expected / explained in readdir(3).

https://github.com/vgough/encfs/pull/356 should then I hope correct the issue, as getAttr will no more follow the links but stat them themselves 👍

**Comment by benrubson** [comment]
> Certainly that readdir() does not set errno as expected / explained in readdir(3).

I wonder if we could use `readdir_r()` instead, as it returns 0 on success or an error number to indicate failure.

**Comment by benrubson** [comment]
If you then have time to compile the following one with `readdir_r()` : https://github.com/benrubson/encfs/commit/bb99bd4d66421f7c807db7833356399c5499c9db
Thank you !

**Comment by jetwhiz** [comment]
I'm not sure how easy this patch will be to apply, since we aren't using readdir in the Windows version (built-in Windows calls are being used to implement this -- see https://github.com/jetwhiz/encfs4win/blob/master/encfs/compatwin.cpp#L751)

**Comment by benrubson** [comment]
I made a mistake in previous `readdir` patch, I reset `errno` after the `readdir` call !
Here is the correct version : https://github.com/benrubson/encfs/commit/990155688ee234edbcb3f191b74d8b2916948783
Sorry for this...

**Comment by benrubson** [comment]
> I think the error is occurring in the getAttr portion of the code

You're right, unix::lstat() returns permission denied, which is rather strange.

Do you think this is due to Dokany ?

Dokany `mirror` does not manage to stat them but does not crash on directory listing (its "getAttr" function must not return the error) :

![sc](https://user-images.githubusercontent.com/6764151/37356591-a74f5c56-26e6-11e8-9342-3f19cfa55841.png)

Dokany `fuse_mirror` shows them as directories (but it's not a nice solution).

Cygwin itself shows them correctly :

![cyg](https://user-images.githubusercontent.com/6764151/37356768-0597773a-26e7-11e8-930d-e95252b1314f.png)

**Comment by benrubson** [comment]
I tried to add `FILE_FLAG_OPEN_REPARSE_POINT` flag to `CreateFileW()` in order to stat links themselves :
https://github.com/jetwhiz/encfs4win/blob/v1.10.1-RC13/encfs/compatwin.cpp#L645
But it does not help...

**Comment by benrubson** [comment]
Reverse mode also fails on some specific files such as `C:\pagefile.sys`
Error is the same as above, permission denied in `getattr`, leading to incomplete `readdir`.
Dokany `mirror` correctly show these files.

**Comment by benrubson** [comment]
#103 may help 👍

**Comment by jetwhiz** [comment]
Great, nice find, @benrubson !   I'll try this out with the modern and legacy Dokan builds
